### ISSUE TITLE
Support of Flash-SocketIO with Waitress

### ISSUE THREAD

**Issue by shadylpstan** [miguelgrinberg/Flask-SocketIO#1010]
Is there any possible way of using flask-socketio with waitress (server supporting both windows and Linux)?

While running I am getting the error : 

> "RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information."

**Comment by miguelgrinberg** [comment]
I don't know if waitress would work, probably not without adding support for it specifically. The eventlet and gevent web servers run both fine on Windows as far as I know, why do you need a third one?

**Comment by spmsh** [comment]
Hi Miguel, I was about to ask the same question as @shadylpstan did. 

The reason is, for prod, we're running our app with nginx/gunicorn/flask-socketio with eventlet. All good, all great.

But we now have requests to run our app on a Windows environment. While we did manage to run the flask-socketio server that is marked as production ready, and deployed it as a windows service, we are still looking for gunicorn alternative on Windows, and we came accross waitress that we're looking at.

More generally, do you know/recommend any good gunicorn replacement for Windows to run a flask-socketio/eventlet app ?

Thanks !

**Comment by miguelgrinberg** [comment]
Both eventlet and gevent have production-level web servers, without having to add gunicorn into the mix. To my knowledge both work fine on Windows.

Another alternative that you have (that may or may not be feasible in your case) is to install your Linux stack on the WSL (Windows Subsystem for Linux). This is actually what I have done many times with good results.
