### ISSUE TITLE
SocketIO scaling for a Deep Learning application

### ISSUE THREAD

**Issue by skyler1253** [miguelgrinberg/Flask-SocketIO#1015]
Hi @miguelgrinberg - I'm wondering if I could get your take on the best way to scale a deep learning application.  I'm using Flask-SocketIO to stream images from a client web cam to a server.  When an image is received on the server side, I send it through a model (pytorch GPU based) that returns another image with some annotations.

With just one server and GPU (aws p2.xl), I can stream this process at about 2.5 frames per second.  I'm trying to figure out how I might increase my frames per second by incorporating multi-threading and multiple GPUs?  Would it make sense to use Redis as a message broker to receive more than 2.5 frames per second, and then have say four different GPUs that are consuming images from this Redis queue? Or are there other ways that would make more sense to scale this (right now thinking about just one client connection, but moving to many?)

**Comment by miguelgrinberg** [comment]
You definitely need to scale your GPUs, but I'm not sure about the web server, which isn't doing much, besides receiving images and sending them over to the GPU for processing.

I would try to implement pipelining in the client and the server, so that they don't sit around waiting for an image to be analyzed. If a single CPU can do 2.5 fps, then you should be able to do about 10 fps with 4 of them, with the caveat that your latency will not improve, since it will still take about 0.4s for an image to be processed, same as with your single GPU workflow.
