### ISSUE TITLE
background task using `threading.Thread` is blocking main thread

### ISSUE THREAD

**Issue by jcuna** [miguelgrinberg/Flask-SocketIO#1041]
Hello there. 

This might actually turn out to be a question but currently I have a long-running background task that spins the app again and does some auditing.

I make sure to only fire the background task when the main thread is created and I `eventlet.monkey_patch()` the MainThread only at the very beginning of the script. Though I also tested monkey patching every thread.

if the background thread has a lot of stuff to audit, it blocks the main thread, the more stuff in memory, the longer it blocks the main thread.

A few more details:
* The items that need to be audited are added to an object in memory from the main thread and are passed by reference to the child thread. (Like a in memory queue)
* If I don't monkey patch eventlet, then everything works fine but then flask's auto reload won't work, and I need it for development. 
* I run the app like `socketio.run(app)` in dev
* Behavior persists when using gunicorn/eventlet

Any help would be highly appreciated. 

Thanks

**Comment by jcuna** [comment]
I also tried using eventlet's green library for sleep and threading but when I do that the thread does not execute any code

**Comment by miguelgrinberg** [comment]
Note that this has really nothing to do with Flask-SocketIO, and everything to do with eventlet and the asynchronous programming model. You will probably get your question seen by a much bigger audience if you post it on Stack Overflow and properly tag it as an async question instead of Flask-SocketIO.

Since you are not showing any code I can't really tell you what's wrong, but you can't really do any lengthy CPU work, since that's incompatible with the async model. If you must do this work, and there is no way you can insert regular sleeps, then I'd say the async model is not a good model for your application.

**Comment by jcuna** [comment]
thanks

**Comment by jcuna** [comment]
Just thought I'd post the stackoverflow question I created. I Also added code examples and more details to it. In case it helps anybody or if anybody from here wants to participate. 
https://stackoverflow.com/questions/57515145/flask-background-task-using-threading-thread-is-blocking-main-thread
