### ISSUE TITLE
flask socketio with gunicorn

### ISSUE THREAD

**Issue by tasnuvaleeya** [miguelgrinberg/Flask-SocketIO#1052]
I am working with a chat app and while deploying the app with gunicorn facing below error. 
My wsgi.py file looks like:

```
from server import app
from flask_socketio import SocketIO
# async_mode = None

socketio = SocketIO(app)

if __name__ == "__main__":
    socketio.run(app)
```
after running this command :
`gunicorn -w 3 wsgi:app` 
facing below error.

Error:
RuntimeError: You need to use the gevent-websocket server. See the Deployment section of the documentation for more information.
Authentication blcok in the server

**Comment by miguelgrinberg** [comment]
See the [deployment documentation](https://flask-socketio.readthedocs.io/en/latest/#gunicorn-web-server) to learn how to use gunicorn to deploy Flask-SocketIO.

**Comment by jgvaraujo** [comment]
pip install eventlet
gunicorn --worker-class eventlet -w 3 wsgi:app

**Comment by miguelgrinberg** [comment]
@jgvaraujo Not sure why you posted here, but your example is also wrong. Please read the docs to see how to use gunicorn with eventlet. Use the link I posted above.

**Comment by tallPaul66** [comment]
FYI (feel free to delete if not helpful): I also get this error message while running a poker app on heroku that uses Flask-SocketIO. I haven't tried the fix you mention in your blog because the error doesn't cause any problem in running the app on the web that I can find. I.e., all web app works perfectly well for all players under all tested conditions and so have no pressing need to prevent the error from happening. Thanks again for all your work on this.
