### ISSUE TITLE
Is there any way to keep a socket connection alive??

### ISSUE THREAD

**Issue by sajil13** [miguelgrinberg/Flask-SocketIO#1063]
I wanted to know If there was a way to keep a socket connection alive even after the default timeout of 60 secs. 

What I am trying to achieve is to keep the socket connection alive if a message from the server takes longer than 60 seconds. I thought that explicitly setting the transport method to WebSocket might help as opposed to the long polling way. Even after using it I didn't find any noticeable difference.

Also is there any way of not queuing the message that is sent by the server. Right now if the server responds with 4 different messages then I call the send function to send each message one by one. I don't know how but it sends the message in a go once the server returns a 200 OK to the client. I haven't enabled message queuing.

**Comment by miguelgrinberg** [comment]
I think you misunderstand the 60 second timeout. It does not apply to your own handlers, that is an internal timeout that regulates how the client and the server maintain the connection active. You can spend as much time as you like in your own handlers, as long as you don't block. If you are running a long calculation or other CPU intensive work, you have to add `sio.sleep(0)` calls often to allow other tasks to get some time on the CPU.

The messages are not really queuing, the problem is similar to the above, where you send a message, but then continue to control the CPU without letting other tasks in the process to run. If you add the sleep calls the messages will be send faster.

**Comment by y-mironov** [comment]
`sio.sleep(0)`  helped me with load testing in Locust

```python
class BaseTasks(TaskSet):

    def on_start(self):
        self.sio = socketio.Client()

    def wait(self):
        self.sio.sleep(0)
        return super().wait()
```
