### ISSUE TITLE
nginx + uwsgi + greenlet bad file descriptor

### ISSUE THREAD

**Issue by dank69** [miguelgrinberg/Flask-SocketIO#1076]
Hello,

I am having the same issue as some other commenters from [issue number 909](https://github.com/miguelgrinberg/Flask-SocketIO/issues/909). However I don't see a resolution there which would work for me.

I am using SocketIO as part of a Flask application. The application is accessed via nginx and run using uwsgi.

The configuration I am using for nginx (with the non-FlaskIO-documented options being added by me in an attempt to resolve the issue):
```
   	location /socket.io {	    
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

      	    proxy_http_version 1.1;
      	    proxy_set_header Upgrade $http_upgrade;
      	    proxy_set_header Connection "Upgrade";
	    
            proxy_buffering off;
            proxy_redirect off;
	    proxy_request_buffering off;

	    proxy_buffers 16 32k;  
	    proxy_buffer_size 64k;
	    proxy_busy_buffers_size 64k;
      	    proxy_temp_file_write_size 64k;

	    proxy_read_timeout 86400s;
      	    proxy_connect_timeout 86400s;
	    
            proxy_pass http://flask_app:5000/socket.io;
   	}
```

The configuration I am using for uwsgi:
```
uwsgi --http :5000 --wsgi-file run.py --callable app --master --gevent 1000 --http-websockets --vacuum --thunder-lock --single-interpreter --threads=1 --buffer-size=65535
```
During application usage, the Socket connection will "randomly die" (however after this the socket will reconnect, I also don't know the exact cause). After the socket dies, I see errors in my logs such as from the other issue:
```
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/lib/python2.7/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 57, in select_greenlet_runner
    select([fd], [], [])[0]
  File "/usr/lib/python2.7/site-packages/gevent/select.py", line 145, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
error: (9, 'Bad file descriptor')
2019-10-06T07:09:05Z <Greenlet at 0x7fc609a1eaa0: select_greenlet_runner(16, <gevent._event.Event object at 0x7fc609c759a8>)> failed with error
```

I am using the following versions:
```
Flask==1.0.2
Flask-SocketIO==4.2.1
gevent==1.4.0
greenlet==0.4.15
uWSGI==2.0.18
```

Any ideas or fixes?

**Comment by miguelgrinberg** [comment]
Have you considered the possibility that this is actually a networking problem, and these sockets are in fact getting closed on the other side? I'm not sure how often this happens, but a flaky network is the most logical explanation. The reconnection part is actually a feature of the Socket.IO client, so that seems to be working well.

**Comment by dank69** [comment]
I don't think this is a networking problem. It seems unlikely as I see the same error in my logs for multiple connections from multiple countries at different times. If I just leave the website open (aka keep the socket alive), the error will occur sometime within 30 minutes. 

I know I don't have networking issues from my location to the server (and it also happens to my connection).

**Comment by igoras1993** [comment]
@dank69 Are you sure?
We are getting the same exeptions but it is higly correlated with network change (on mobile devices for example, switching from WiFi to LTE etc.)
It still might be a network problem.

**Comment by dank69** [comment]
Interesting.. any tips on solutions/debugging?

**Comment by 0x78f1935** [comment]
I encounter the same issue currently, We host in google cloud through docker environments.
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 57, in select_greenlet_runner
    select([fd], [], [])[0]
  File "/usr/local/lib/python3.7/site-packages/gevent/select.py", line 145, in select
    sel_results = _original_select(rlist, wlist, xlist, 0)
OSError: [Errno 9] Bad file descriptor
2020-02-11T08:25:38Z <Greenlet at 0x7fa1e81544d0: select_greenlet_runner(7, <gevent._event.Event object at 0x7fa1f642dd70>)> failed with OSError
```
No clue why this happens currently, normally our servers are running 24/7 without issue. When building the docker environment it always takes the latest version of packages. The last build I deployed was perhaps last friday Since it brings up this issue. I dunno if a new update of gevent rolled out in the mean time but perhaps downgrade?

**Comment by miguelgrinberg** [comment]
@0x78f1935 I can't offer any advice on this problem, but just wanted to mention that you should pin your dependencies. It's crazy to deploy with latest packages every time. It sort of invalidates any testing that you do on your own, since each deployment brings new code into the mix.

**Comment by jorgensoares** [comment]
Are you using uwsgi? there was a new release last Sunday:
https://pypi.org/project/uWSGI/#history

**Comment by 0x78f1935** [comment]
@miguelgrinberg Don't worry you have teached me enough already with the articles you make. I really enjoy those! :) @jorgensoares was right, I did some testing and was not able reproduce the issue after rebuilding our docker environment. Our build takes the latest installation of uwsgi and ever since I've rebuild our environment it worked again. So after all it was just a "did you try to turn it on and off again". Thank you both. =)
