### ISSUE TITLE
Websockets with cpu bound routes 

### ISSUE THREAD

**Issue by BenStorey** [miguelgrinberg/Flask-SocketIO#1101]
Hello, 

We have a fairly simple flask web service that uses this library for Web socket communication, and it's been working well so thank you for that!

Recently we added some new routes that will spawn background threads, but these are mainly CPU bound. This doesn't work well with eventlet because they don't yield and will cause the service to hang. 

So ideally we'd like to sit behind gunicorn and use a real thread per request, but the socketio gunicorn documentation seems to always require gunicorn to be started using eventlet or gevent also? 

Is there any way to use socketio and gunicorn together whilst only ever using native os threads? Or any other setup that might work better here? Seems a little sad we can't have both websocket support and any cpu bound routes at the same time :) 

Thank you!

**Comment by miguelgrinberg** [comment]
This is always tricky. Maybe an eventlet thread pool will help? https://eventlet.net/doc/threading.html.

In any case, also keep in mind that thread concurrency in Python isn't that great because of the Global Interpreter Lock, so even if you manage to send your CPU bound tasks to other threads, things may not smooth as you expect.

You can also consider using a work queue and send your CPU jobs to worker processes. Celery or RedisQueue are both good at this.

**Comment by BenStorey** [comment]
Thanks Miguel,

Eventually I went with Celery work queues and that is working well for me. I was trying to avoid the added complexity of deploying more infrastructure just for this, but I think it will payoff in the long run.

Cheers
