### ISSUE TITLE
greenlet.error: cannot switch to a different thread

### ISSUE THREAD

**Issue by leveraction** [miguelgrinberg/Flask-SocketIO#1102]
Trying to use Flask socketio hosted on AWS EB and get the following in the logs.

> [Thu Nov 14 19:48:47.741977 2019] [:error] [pid 5178] Traceback (most recent call last):
> [Thu Nov 14 19:48:47.742018 2019] [:error] [pid 5178]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/eventlet/queue.py", line 118, in switch
> [Thu Nov 14 19:48:47.742023 2019] [:error] [pid 5178]     self.greenlet.switch(value)
> [Thu Nov 14 19:48:47.742040 2019] [:error] [pid 5178] greenlet.error: cannot switch to a different thread

I attempted:
```
if __name__ == '__main__':
  # see https://github.com/miguelgrinberg/Flask-SocketIO/issues/65
  from gevent import monkey
  monkey.patch_all()
  socketio.run(application, debug=True)
```
and also attempted adding the monkey patch code to the top of application.py as well. In either case I get the same in the logs. Does anyone have any suggestions?

**Comment by miguelgrinberg** [comment]
I've seen this error when an application is not monkey-patched, or is monkey-patched too late. In any case, EB is not the right hosting platform for this type of service, the auto-scaling/load-balancing that EB does is unlikely to work well with Socket.IO, which needs a stable deployment that does not constantly change based on load.

**Comment by leveraction** [comment]
Mmmm....So I included the monkey-patch code, so presumably it can't be that it isn't monkey-patched.  What do you mean by too late?  What could I do other than add the patch to application.py?
So auto-scaling/and load balancing don't work well with Sockets.IO?  What do you suggest?  Simply not using a load balancer? (or auto-scaling)  Why would that be a problem so long as connections with a given client are consistent? I wonder if it would be possible to use another non-scaling server for the sockets, at the risk of further complicating my little project.  It this an issue with the Flask implementation of web sockets or web sockets in general?  Thanks for your quick reply.

**Comment by miguelgrinberg** [comment]
> What do you mean by too late?

In general you'd want to call the monkey patching function as the first thing you do. This would be above everything else, including other imports. Monkey patching basically alters the import subsystem in Python so that all these incompatible things are redirected to the eventlet provided versions, if you start importing things before monkey patching you may end up having the non-monkey patched versions. This is what I mean by doing it "too late'.

**Comment by leveraction** [comment]
I added the patch code to the top and still get the same in the logs so I guess there is another issue floating in here somewhere.  I am also working with the paid developer help and AWS and will post a solution here if I get one.  Hopefully, I can get this resolved quickly.

**Comment by miguelgrinberg** [comment]
> So auto-scaling/and load balancing don't work well with Sockets.IO? What do you suggest?

Sorry, forgot to answer your second question. Auto-scaling is in general not a good idea, because each time the number of servers go up or down the mapping between clients and servers changes. Any client that ends up being moved to another server during a scaling event will lose the connection and will need to reconnect.

Load balancing is not a problem as long as you use sticky sessions. Without sticky sessions long-polling clients will not work. Websocket clients will be okay, as long as they connect directly via websocket. Normal clients connect via long-polling first and then upgrade, so these will not work without sticky sessions.
