### ISSUE TITLE
Integrating Flask Socket.io with Unreal engine 4 (UE4) 

### ISSUE THREAD

**Issue by hghaffar2** [miguelgrinberg/Flask-SocketIO#1176]
When trying to test the connection between UE4 and flask socket.io, there was an error number 400.

Here is the code that I tested.
from flask import Flask, render_template, request
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, cors_allowed_origins='*')

@app.route('/')
def index():
    return render_template('index.html')

@socketio.on('chat message')
def handle_my_custom_event(data):
    print(request.sid)
    print('received json: ' + str(data))
    emit('chat message', data, broadcast=True)

if __name__ == '__main__':
    socketio.run(app)

**Comment by miguelgrinberg** [comment]
Did you see the request for logs in the issue template? Here is the relevant section in case you missed it:

**Logs**
Please provide relevant logs from the server and the client. On the server, add the `logger=True` and `engineio_logger=True` arguments to your `SocketIO()` object to get logs dumped on your terminal. The same arguments can be used on the [python-socketio's client](https://github.com/miguelgrinberg/python-socketio). If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

Please be mindful of my time and provide the information that is requested so that I can help you figure this out.

**Comment by hghaffar2** [comment]
Thank you for your swift reply and we have solved our issue 
through the attached link in your repo

https://github.com/miguelgrinberg/Flask-SocketIO/issues/489
