### ISSUE TITLE
Performing one-time initialization steps and using a multiple workers pattern.

### ISSUE THREAD

**Issue by igoras1993** [miguelgrinberg/Flask-SocketIO#1195]
Hi, currently we are making some decisions on making real use of flask's `before_first_request()` utility. I am wondering on pattern presented by You in documentation (Using Multiple Workers section) and how it will perform in conjunction with `before_first_request()` decorator.

I am using uWSGI as an application server, behind Nginx proxy of course. We want to perform some one-shots  on database and/or global application memory (uwsgi cache). Currently it is no problem - there is only one uwsgi application server. Moving to multiple nodes pattern will force on us using an central cache instance, but this in not the problem, as uwsgi supports communication with its external cache servers (or redis can be then used as well).

The one thing that concerns me is those one-shots. If using pattern that You are suggesting in docs, and placing one-shots inside `before_first_request()`, they actually will shot as many times as number of nodes, right?

Even placing one-shots while app initialization (`init_app()` approach of course) will not work, because it is now more similar to a uwsgi `lazy-apps` param set in conjunction with `processes=n`.

I am asking You about suggestions on how to achieve my goal using approach proposed by You in a docs? Any =PRO TIPS= :) ?

**Comment by miguelgrinberg** [comment]
I'm sorry, but I think you are confusing Flask with Flask-SocketIO. The `before_first_request` decorator is for Flask. This issue board is for Flask-SocketIO, not Flask. I'm not sure what recommendation you say I made in documentation. Which documentation? I did not write the Flask documentation.

**Comment by igoras1993** [comment]
No, I am not confused. Here You are describing Your approach for scalling flask-socetio application with multiple workers:
https://flask-socketio.readthedocs.io/en/latest/#using-multiple-workers

Since You bothered describing that, I've assumed that it was important for flassk-socketio users, right?
Especially I am intrested on Your advices, because of this Issue:
https://github.com/miguelgrinberg/Flask-SocketIO/issues/535

Where You just pointed out that regular scalling solution with `uwsgi` web server is not the one that You would use for flask-socketio. Scalling flask app on `uwsgi` web server was usually as simple as adding `processes=n` in `uwsgi` config. Here You are recommending essentially different solution.
 So yes, I am assuming that my question should be addressed in this repo, not `flask` or `uwsgi`...

**Comment by miguelgrinberg** [comment]
I still don't understand what is the question, sorry.

You are correct, Flask-SocketIO has to be scaled in a very specific way, as described in the documentation. Are you asking if the behavior of the `before_first_request` decorator changes when you scale in this way? The answer is no, the decorator works in exactly the same way as when you scale by changing the number of processes. Basically each process will run its own `before_first_request` handler, so if you have 10 processes, your handler will run 10 times, one for each process. This is true for Flask and Flask-SocketIO, regardless of how you scale your processes.

**Comment by igoras1993** [comment]
Ok, that is one thing, thanks for that, but...

`uwsgi` will initialize app only once (unless one will set `lazy-apps` flag). Here, N initialization will happen, right? 

If so, I can't just place my "one-shots" just at the end of an `init_app`. My question is: do you have any special advice on performing one-shots (per "project") with your approach for scalling?

**Comment by johaven** [comment]
If you want to redirect socketio traffic to specific worker you can do this with uwsgi:

```ini
processes = 4
socket = $(PWD)/run/socket_http
socket = $(PWD)/run/socket_ws
map-socket = 0:1,2,3
map-socket = 1:4
```
This will dedicate 1 worker for the web socket.
In nginx you can finally do something like this:

```conf
location /socket.io/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        include uwsgi_params;
        uwsgi_pass unix:/path/to/project/run/socket_ws;
    }
```

I think all proxy_* directives are useless because uwsgi handle websocket traffic over sockets for some time.

**Comment by miguelgrinberg** [comment]
@johaven your configuration is incorrect. The HTTP long-polling transport needs sticky sessions, not websocket.

**Comment by johaven** [comment]
@miguelgrinberg The HTTP long-polling will be redirected to _socket_ws_ (because nginx redirect it with location url) which are dedicated to one uwsgi worker. All sessions will be stored on same memory space (1 worker == 1 process).

**Comment by miguelgrinberg** [comment]
Okay, I see now, so what you are calling `socket_ws` is not really websocket, the name is misleading.

So basically you are still using a single worker for Socket.IO. I would not recommend this type of set up. If you are going to strictly separate workers that do standard Flask stuff versus from the single worker that does Socket.IO I would rather create separate processes, so that the Flask stuff isn't using up memory in the Socket.IO process and viceversa. No need to load both sides of the application into every worker if each worker is concern with just one side.

**Comment by johaven** [comment]
I know it's not very optimal but it's depend of your usage of socketio.
The memory consumption of a worker for a medium-sized flask project is limited (personally I am between 30/50 MB)
If you want to use socketio without restructure all your code, it's a low cost.

The second thing which makes me say that this is not such a bad solution, it is that in production the workers are generally restarted regularly in particular after a certain number of requests (max-requests option in uwsgi). This has the effect of closing the ws connections and causes the reconnection of clients that were hosted on the worker. By partitioning these connections on a worker which will not process API requests, we reduce this effect and the traffic generated by worker reloads.

If you want to do ip_hash via nginx to a local unix or tcp socket, you need in all cases to partition each socket by worker otherwise it doesn't matter (or you have to create a master process uwsgi by socket, which is worse in terms of memory consumption). When we declare 4 sockets in uwsgi, the data is shared on all workers without the configuration that I posted above.

**Comment by igoras1993** [comment]
@johaven interesting piece of configuration, I will remember such possibilities for the future. For me, it is not that useful, because it does not scale a socketio part of application (in my case, a main line of app is relies on socketio). But if someone does not load heavy stuff on socketio part of app - sure, why not. Easy way for scalling http part.

If anyone ever wondered how we've ended up: 
We have decided that one worker will serve master-like purposes. Application initialization steps that are operating on common storage (database/cache) and thus have to be performed only once - are now fired in one master worker, which has just slightly modified code than other node workers.  That way we can still scale app and have ``master=true`` like behaviour.

But since contenerization approaches us really fast, holding one-shots inside app will likely be questioned now :)
