### ISSUE TITLE
Bundle authenticated_only decorator with the library

### ISSUE THREAD

**Issue by TaaviE** [miguelgrinberg/Flask-SocketIO#1248]
Would it be possible to bundle the decorator with the library? 

A lot of people use the decorator in their projects, it is currently described in the documentation but it would be very nice if the library just had it bundled so that people could simply import it.

This would provide a pythonic one good way for everyone.

**Comment by miguelgrinberg** [comment]
For the same reason Flask does not include authentication I tend to prefer not having authentication in the Socket.IO server. You say that it would be the "one good way for everyone", but that is actually not true. Some examples where the decorator would not work:

- If you don't use Flask-Login for authentication
- If you want to perform authentication directly in the Socket.IO connection instead of through a regular HTTP route
- If you want to handle non-authenticated users in a way that is not to disconnect them

**Comment by TaaviE** [comment]
Of course those caveats apply. But those caveats can be nicely documented. The current docs could just have a line "If you want, this decorator can be imported with `from flask_socketio.login import authenticated_only`".

**Comment by TaaviE** [comment]
It would be nice to have `Flask-SocketIO-Security` but just for one decorator it seems a bit like overkill. :/

**Comment by miguelgrinberg** [comment]
I think if you were to create a Flask-SocketIO-Security package it would grow to a monster size (like its Flask-Security counterpart) to allow for the million different ways to do security.
