### ISSUE TITLE
use of app.run vs. socketio.run

### ISSUE THREAD

**Issue by mhechthz** [miguelgrinberg/Flask-SocketIO#1273]
Hi,

I wonder about the usage of `app.run` vs. `socketio.run`. I have in my code '__main__':
```
  port = 8081
  app = create_app(port)
  socketio = app.extensions['socketio']
  socketio.run(app, port=port,host='0.0.0.0',debug=True)  
  # app.run(host='0.0.0.0', port=port, debug=True, threaded=True)    
```
 to be compatible with `gunicorn`. If I now run `app.run` instead of `socket.run` with the `Flask-Server` the application doesn't work. Mainly `socketio.start_background_task` is not executed properly. Running gunicorn gets only back the `app ` to run and nevertheless finally works perfect.

So what is the difference and why I cannot use always `app.run`?

**Comment by miguelgrinberg** [comment]
The `app.run()` function starts the Flask dev web server. The `socketio.run()` function starts a Socket.IO enabled web server. Gunicorn does not use `app.run()` nor `socketio.run()`, so I don't understand what the problem is.

**Comment by mhechthz** [comment]
Oh, ...
running gunicorn I have the method create_app, that is called and gives back the app object:
`
gunicorn -k gevent --timeout 60 --log-level info --workers=1 -b 0.0.0.0:10001 'oi_socketio_app:create_app(10001)'`
and
```
def create_app(port):
  
  global glob
  glob = {}

  glob['port'] = port

  async_mode  = 'gevent'
  app         = Flask(__name__)
  socketio    = SocketIO(app, async_mode=async_mode)

  global thread, thread_lock
  thread      = None
  thread_lock = Lock()

  setupEndpoints(app,socketio)

  return app
```
So I thought, that `gunicorn` somehow uses the returned app??? I do it like this, because I found it in the web. Without `gunicorn` I run the `socketio.run` from the main routine. 

So how does gunicorn now how to run the right `*.run` call?

**Comment by miguelgrinberg** [comment]
Nothing you asked seem stupid, I just said that I did not understand what the problem was, because you didn't really indicate you were having a problem.

Flask-SocketIO needs a web server. There are a few that you can use:

- The Gevent web server, started via socketio.run()
- The eventlet web server, also started via socketio.run()
- The Flask dev web server, which can be started either via app.run() or for convenience also via socketio.run()
- The Gunicorn web server with the eventlet or gevent workers, started via the gunicorn command.

The `socketio.run()` function just checks to see which web server you indicated you want to run on (via the `async_mode` argument, or by looking at the installed packages) and starts that server. It knows how to start the gevent, eventlet and the Flask servers. It doesn't do anything else besides that, so no magic at all.

If you don't want to use `socketio.run()` it's totally fine, you can start your own web server, as long as it is one of the supported ones. You are actually doing that when you run on Gunicorn.

**Comment by BassThatHertz** [comment]
I'm not the OP but I'm seeking a quick clarification. I have `socketio.run()` in my Flask app (main.py):
```
if __name__ == "__main__":
    socketio.run(app, host='0.0.0.0')
```
And I run the Flask app with Gunicorn:
`gunicorn3 --bind 0.0.0.0:8000 -k eventlet -w 1 main:app`

I noticed that you said Gunicorn does not use `app.run()` or `socketio.run()`, so what is the significance (if any) of the `socketio.run(app, host='0.0.0.0')` that I have in my Flask app (main.py)?

**Comment by miguelgrinberg** [comment]
@BassThatHertz the code that is inside the `if __name__` conditional will only run when you execute the script directly with `python script.py`. When you run with gunicorn or any other web server this file will not be the main script of the application, so the conditional will be `False`.

**Comment by BassThatHertz** [comment]
@miguelgrinberg Got it. Thanks.

**Comment by Ahzam-Lathiya** [comment]
@miguelgrinberg Any Idea how it works with **wsgi.py** file. My main app is in for example **application.py**  without the ** if __name__** part and within the same directory I have wsgi.py  file which is:
`from application import app

if __name__ == "__main__":
    app.run()`

I run it with **gunicorn --worker-class eventlet -w 1 wsgi:app**
I'm not getting any errors , just confused and wanted to find out what significance does the **wsgi.py** brings. My app runs fine with or without it.
Thanks

**Comment by miguelgrinberg** [comment]
If you use gunicorn then any code that you put inside the `if __name__ == '__main__'` conditional is not used. That code only runs when you run wsgi.py as your main script, such as `python wsgi.py`. The only think gunicorn cares is your `app` variable.

**Comment by kr-prince** [comment]
@miguelgrinberg sorry if this is redundant, but could you please explain in a bit more simple way how do I replace the `threaded=True` param in app.run while I am using socket.run. Refer the first comment in this thread. 
`# app.run(host='0.0.0.0', port=port, debug=True, threaded=True)`
I checked the docs and read about using load balancers. Is their any simpler way?

**Comment by miguelgrinberg** [comment]
The threaded option only makes sense when you use the Flask development web server, and for Socket.IO to work it has to be set to `True`. Since this option cannot be changed when using the dev server, and it isn't used when using a different server, there is really no situation in which you need to handle it manually.

**Comment by shubham088** [comment]
HI, i am calling one api which is calling other 2 api's using requests module. if i am using app.run(debug=True) it is working fine and i am getting proper response but if i use socketio.run(app, host="0.0.0.0", debig=True) i am getting connection reset error .
Do u have any suggestion over it? what could be the solution?

**Comment by Ahzam-Lathiya** [comment]
hey @shubham088 if there is a connection reset error. Then maybe because the connection is being timed out. Also the requests module in python calls APIs in a blocking manner. You need to run it in a non-blocking manner. Use eventlet or gevent and monkey_patch your entire code. This will change all of your default blocking code to non-blocking. Also you need to use the gunicorn server which won't be run with neither app.run() nor socketio.run(). You should run the app using the gunicorn command using the eventlet or gevent workers which will make the server asynchronous.

**Comment by shubham088** [comment]
@Ahzam-Lathiya , i have tried monkey.patch_all() before all the imports but still i am getting the error. Exactly, i am getting "requests.Exception.ConnectionError : ("Connection Aborted","Remote Disconnected ")".
while commenting socketio.run(app) , i am getting the required output. can you help me here? 
I tried with grequest, request.Session, request_future also but no result

**Comment by shubham088** [comment]
basically if i am running socketio.run(app) i am getting above error but if i use normal app.run() api is getting executed
