### ISSUE TITLE
Flask-socketio is disconnected after ping/pong data None

### ISSUE THREAD

**Issue by aj-super** [miguelgrinberg/Flask-SocketIO#1274]
These images are showing source code and logs.
Can you please let me know why it's disconnected after done connection.
![image](https://user-images.githubusercontent.com/34548664/81338954-72d28d80-907b-11ea-9e3f-97de3824cf4a.png)
![image](https://user-images.githubusercontent.com/34548664/81339228-ce048000-907b-11ea-8155-c987c6da5264.png)
![image](https://user-images.githubusercontent.com/34548664/81339124-ac0afd80-907b-11ea-84d3-08daaa815e1a.png)

Why is this sending ping/pong data None?
And, after some time, it's disconnected with saying client is gone, closing socket.
Looking forward to hearing from you asap.
Thanks.

**Comment by miguelgrinberg** [comment]
You appear to have two servers initialized in the same process. Note the "server initialized for..." lines, you've got two of them, one for eventlet and one for threading. There should be only one server. Not sure if this is causing your problem, but a good start would be to address that.

**Comment by tiny-1996** [comment]
ah.. sorry. I sent wrong image. Please look at this screenshot again.
![image](https://user-images.githubusercontent.com/34548664/81356661-b4752f80-909f-11ea-9b20-7ce0b33efdba.png)

**Comment by tiny-1996** [comment]
As you can see, there are two initialization in my scripts now.
In main script, i get socketIO instance like as following:
```
socketio = SocketIO(app, 
                    async_mode='threading', ping_timeout=200,
                    message_queue='amqp://user1:password@localhost:5672//', 
                    cors_allowed_origins='*', engineio_logger=True)
```
And, in another script, i get the instance like as following:
```
socketio = SocketIO(async_mode='threading', ping_timeout=200,
                    message_queue='amqp://user1:password@localhost:5672//', 
                    cors_allowed_origins='*', engineio_logger=True)
```
And then, i'm emitting message to one event in frontend from backend like:
socketio. emmit ( "receive event", "message" )

**Comment by tiny-1996** [comment]
So, in another script, i used multi-processing. That's why i used message_queue for getting the right instance and emit state message to frontend in real time.

**Comment by tiny-1996** [comment]
But, as you can see above screenshots, socketIO is disconnected after some time. Because of that, i can get 400 Bad Request Error frequently and messages are not reached from backend to frontend.
Do you know why it's disconnected?

**Comment by tiny-1996** [comment]
Hi @miguelgrinberg 
My scripts and error log file are here: https://drive.google.com/open?id=1Hdp_bJiYY9BMSvqE8vSaQzVAITdLD_Iq
And the temporary site url: http://100.26.108.34
In the site, you can see 400 Bad Request errors are coming up frequently due to being disconnected.
Looking forward to hearing from you as soon as possible. Thanks.

**Comment by miguelgrinberg** [comment]
Couple of notes (likely unrelated):

- Don't mess with the Socket.IO timeouts. The defaults are correct for 99.9% of cases.
- No need to sleep(0) after each emit.

The log that you shared suggests your clients are not following the Socket.IO protocol. I cannot see your clients, and your site appears to be down right now, so that is as much as I can tell you.
