### ISSUE TITLE
Alternative to decorators

### ISSUE THREAD

**Issue by richburdon** [miguelgrinberg/Flask-SocketIO#129]
It would be useful to support the private _on_message() API (as well as other calls) as an alternative to the decorator pattern (similar to Flask routes).

    app = Flask(...)

    @app.route('/') # Alt 1
    def home():
      pass

    app.url_map.add(Rule('/', endpoint='home')) # Alt 2

Decorators have global scope which means they cannot be used with Flask-Injection. Suppose I have a resource (e.g., Database) that is injected at runtime. 

    @inject(database=Database)
    class SocketHandler(object):
      def on_message(self, message):
        self.database.query(message)

With the current API, it is extremely cumbersome to make this work.

    @socket.on('message')
    def on_message(message):
      # HOW TO CALL MY HANDLER?

**Comment by miguelgrinberg** [comment]
I'm not sure I see the problem. But in any case, the `on` decorator does not need to be used in the global scope. You can, for example, do this:

    def my_function():
        def my_message_handler(message):
            pass
        socketio.on('message')(my_message_handler)

This isn't available in the current release, but I am planning to extend the `on` function so that you can also do it like this:

        socketio.on('message', my_message_handler)

Does this address your problem?

**Comment by richburdon** [comment]
Ah, yes, I was confused -- that works fine. Thanks.
