### ISSUE TITLE
Cleaning cache every time front-end code is updated

### ISSUE THREAD

**Issue by luisArandas** [miguelgrinberg/Flask-SocketIO#1310]
Hello!

I think this is a silly question but I can't figure out a quick way around it.  

I am using this library and when I am working on the front-end, every time I update a .js file (not with index.html) of my app I need to clear cache of the browser to test the newly introduced code (currently working with Chrome vs 83.0.4). When working with node and yarn this seems to not be the case. Is there any quick way around it? The objective would be every refresh to get the new saved files. 

I saw the flask-cache library but before I turn that way I want to be sure I am doing everything the right way. 

Thanks in advance.

**Comment by miguelgrinberg** [comment]
Browsers try to cache unless told otherwise. There are a few ways to handle this:

- You can use the "hard refresh" key to refresh (Ctrl-F5 on Windows, Cmd+Shift+R on Mac)
- On Chrome, if you have the developer tools open, go to the Network tab and check the "Disable cache" option. Then a refresh always ignores the cache, as long as dev tools remains open)
- Set the [SEND_FILE_MAX_AGE_DEFAULT](https://flask.palletsprojects.com/en/1.1.x/config/#SEND_FILE_MAX_AGE_DEFAULT) configuration option to 0 and then browsers that honor caching directives will not cache your static files.

Hopefully one of these will work for you!
