### ISSUE TITLE
How do we switch to msgpack?

### ISSUE THREAD

**Issue by rosejn** [miguelgrinberg/Flask-SocketIO#1314]
I don't see any examples on how to use msgpack as the wire encoding with flask-socketio, but it seems to be a fairly standard option for socketio-client in the browser.  Just passing the python msgpack module for the json parameter when instantiating the server doesn't work.  Although msgpack does provide dumps and loads, it seems there are some assumptions made that don't quite fit:

* engineio is passing a separators kwarg which isn't used in msgpack
* msgpack returns bytes rather than strings, which cannot be concatenated in the same way

If you can provide some guidance I'm happy to help do the work, but before hacking away I wanted to see if there might be an existing solution or another mechanism to use msgpack.  Thanks!

**Comment by rosejn** [comment]
This is the library I'm attempting to use on the other end: https://github.com/darrachequesne/socket.io-msgpack-parser

**Comment by miguelgrinberg** [comment]
This is not currently possible, but there is already a way to use an alternative JSON parser/encoder, so that mechanism can be extended to support non-JSON options as well. I believe the main thing that needs to be done is to remove the assumption that encoded payloads are text based. This will need to be done likely in both the python-engineio and python-socketio packages.
