### ISSUE TITLE
Cannot Emit From Route 

### ISSUE THREAD

**Issue by liua13** [miguelgrinberg/Flask-SocketIO#1355]
I'm having trouble understanding why my following code does not work. When the user logs in, I want to create a room based on that user's email. I tried two different ways. The first, I tried calling join or join_room, both of which did not work. When I tried socketio.join(email), I got an error saying that socketio doesn't have a join and when I tried socketio.join_room(email), I also got an error.
```
@app.route("/login", methods=["GET", "POST"])
   def login():
      ...
      if userisloggedin:
         socketio.join(email) # OR socketio.join_room(email)
```

The second way I tried was to emit from the function and create the room separately:

```
@app.route("/login", methods=["GET", "POST"])
   def login():
      ...
      if userisloggedin:
         socketio.emit("privatemsg", email, namespace="/messages") 
 
@socketio.on("privatemsg", namespace="/messages")
   def gotMessage(email):
      print("JJJJJJJ")
      socketio.join_room(email)
```
When the user logs in, the server should print "JJJJJJJ", but it doesn't show up! Why can't I emit from @app.route?

**Comment by miguelgrinberg** [comment]
In your first attempt you are trying to call the `join_room()` function in an HTTP route, which have no idea about the Socket.IO client that matches the HTTP client. This function should be called from a Socket.IO event handler, so that the details about the client connection are known.

In the second example you appear to be trying to send a message from the HTTP route to a Socket.IO handler, both in the server. That's not how emit works. The emit call sends an event to a client, not within the server.

The correct way to do this is this: when the user logs in via HTTP, put something in the user session, like maybe the email address. Then when the same user connects via Sockert.IO the email or other identifying details can be obtained from the session, and at that point you'll be in a Socket.IO event handler, so you can call `join_rooom`. How this helps.

**Comment by liua13** [comment]
Thank you, that does help! The thing is, I also had in the client, but I did not receive an alert message:
```
messagesSocket.on("privatemsg", () => {
    alert("privatemsg");
});
```
Also, I have a flask-wtf form that I'm using to get the user's message (for example if I'm logged in and want to send a message to my friend) and I want to first validate it before emitting. If I shouldn't emit and can't call `join_room()` from a HTTP route, how can I validate the form with socket.io?

```
# server
@socketio.on("message")
def chat(payload):
    form = SendMessageForm(formdata=MultiDict(payload["form"]))
    print(form.validate())
```
```
# client
const socket = io("http://localhost:5000);
$("form[name='sendMessageForm']").submit((event) => {
   event.preventDefault();
   socket.emit("message", {
      senderEmail: "{{email}}",
      form: {
          recipientEmail: $("#recipientEmail").val(),
          message: $("#message").val(),
      },
   });
});
```
`form.validate()` always returns False, which I believe may be because `payload["form"]` doesn't have the `csrf_token` field, which I can't manually add to the socket emit object.

**Comment by miguelgrinberg** [comment]
I can't really tell you what's wrong from looking at snippets. My suggestion is that you start from a working example and modify it to meet your needs. You are obviously making some mistake somewhere.

I don't really understand your second question. Can't you just disable CSRF protection on this form? If you are using this form only with Socket.IO then CSRF attacks are not really possible.

**Comment by liua13** [comment]
Thank you so much for your help! For anyone else experiencing the same issues as me, I figured out what my problems were:
- The reason why I did not receive an alert message was because the client had not connected. I had to first render the view, then emit from the client side when I was connected. 
- For the second problem, I passed in, as a parameter, `meta={'csrf': False}` to override the default CSRF validation. My form then became: `form = SendMessageForm(formdata=MultiDict(payload["form"]), meta={'csrf': False})`.
