### ISSUE TITLE
Docs bug: on("message")

### ISSUE THREAD

**Issue by richburdon** [miguelgrinberg/Flask-SocketIO#140]
https://flask-socketio.readthedocs.org/en/latest/#flask.ext.socketio.SocketIO

Docs say: "The name of the event. Use 'message' to define a handler that takes a string payload, 'json' to define a handler that takes a JSON blob payload"

But the code sample says:

@socketio.on('my event', namespace='/chat')
def handle_my_custom_event(json):
    print('received json: ' + str(json))

It's not clear if the 'message' variable can be used for routing (i.e., supporting different user names) or if there are just 4 legal values ("json", "message", "connect", "disconnect"). Arbitrary values seem supported. But in either case, the sample doesn't match the docs since the string "my event" is not one of the 4 implied values.

**Comment by miguelgrinberg** [comment]
I think the documentation on this place can be made more clear. The idea is that you can use five different values for the `on()` decorator: `message`, `json`, `connect`, `disconnect` and a custom name.

Nowhere in the documentation there is a suggestion that this is equivalent to routing. These are event handlers, you can use the predefined events, or you can create a custom event.

**Comment by richburdon** [comment]
OK, IMVHO those are strange semantics: i.e., mixing three different aspects: i.e., event type ("connect"), data type ("json") and message name "my event".

By "routing" I just meant the notion of custom event names (I wasn't being clear).

**Comment by miguelgrinberg** [comment]
I agree, it's not intuitive. In the 0.x releases, I simply preserved the names for these events given in the gevent-socketio project. And now I decided to keep that the same, so that existing applications do not break.

**Comment by richburdon** [comment]
Yeah, backwards compatibility is hard :(.

**Comment by richburdon** [comment]
Miguel, just on this subject of events: I see that the "sid" property is set on the flask.request which uniquely identifies the socket. But how can this be used to identify a particular client? We can't use sessions or cookies since there may be multiple clients in the browser. My workaround today is to encode the client ID in each message from the client, which is cumbersome.

E.g., the Google websocket (aka channel) API exposes the sid when the channel is created (server-side) so that the serving app can store the <sid x client_id> association.

**Comment by miguelgrinberg** [comment]
Yes, you can use `request.sid` to uniquely identify each client, event for clients that share the same browser. In fact, I use the sid to tie each client to its session.

I haven't tried this, but based on how the mapping from sid to session works, I think when you have multiple clients in the same browser instance, each will get its own private copy of the user session, which may work just fine for your needs. So the server can modify these sessions, and they'll be independently maintained for each client, even though they originate from a single HTTP based session.

Keep in mind that the sessions that are exposed to socket event handlers are sort of a "fork" of the real session, since any changes you make during the socket interactions are not propagated back to the original session (because there is no HTTP vehicle to deliver the changes back to the client cookie).

**Comment by richburdon** [comment]
Right, I saw that the session is a "fork" as you say. That makes sense.

But, I still don't understand how you initially tie the sid to the client (or any server side notion of the client). Nothing else in the session is unique. So unless the client sends its own ID (which is too late for "connect") then I don't see how to do this.

The point I was making about the Google API is that the sid is exposed as you "launch" the client (on the server) so you can assign a client ID there and then store an association to the sid. Do you see what I mean?

All of this can be worked around, but it makes dealing with socket and non-socket clients very cumbersome (since socket clients can't be assigned an ID until connect). So just feedback on the API. 

(Thanks again for the time you're putting into the module -- and for responding to all of these questions).

**Comment by miguelgrinberg** [comment]
> But, I still don't understand how you initially tie the sid to the client

The sid is a random string that the server generates when it receives a connection request. Nothing magical about it.

The association is not with the client, but with the client session. The request that begins a socket connection carries the Flask session cookie, so the association between the sid and the client can be made at that time. The contents of the session are preserved in memory after that, so that it can be restored every time an event arrives from the client. On these subsequent requests the client sends the `sid` that the server assigned to it, so again, it is easy to find the session.

**Comment by richburdon** [comment]
Sorry if this is taking up too much time, but:

> so the association between the sid and the client can be made at that time.

No I don't see how that's possible in a general case (it may be an edge case, but it's the situation I have....) The server doesn't know _which_ client is connecting (imagine multiple clients connecting at the same time -- all from the same authenticated user, hence the same session; e.g., a web page and a chrome app both launching for the first time). So multiple SIDs will be generated (I assume). Then, the client would need to do another handshake (post connect) to identify itself (using it's application ID). 

Hence the (I think) advantage of the Google channel protocol, which generates the SID in advance of the "connect" so the server can configure the client, and the client then connects, sending this SID to the server.

Anyway, as I say this is all pretty esoteric -- just wanted to be clear since we'd come this far in the discussion :).

**Comment by miguelgrinberg** [comment]
> The server doesn't know which client is connecting

Correct, the server just knows that there is a new client that hasn't been seen before. If two connect requests come from the same client machine, then they'll be treated as two separate clients, and each will get its own `sid`. These two clients will have the same session data, but each will get an independent copy of this data.

I think you can use `socket.sid` on the client-side to get the assigned `sid`.

> Then, the client would need to do another handshake (post connect) to identify itself (using it's application ID).

In the case of long-polling, the response to that first connection request includes the generated `sid`. The client will then send that `sid` with all future requests. When the server receives a request that includes a `sid`, it knows it is from a known client, so it finds the data associated with that `sid`.

In the case of WebSocket, the connection request is upgraded to a persistent connection, so the link to the client is never lost.

It's totally possible that I'm not seeing the whole picture, and that is why I don't understand what is it that you can do with the Google Channel API that the Socket.IO handshake does not support.
