### ISSUE TITLE
Flask-socketio with cookiecutter

### ISSUE THREAD

**Issue by atomtm** [miguelgrinberg/Flask-SocketIO#1413]
Hello! I came across this : https://github.com/cookiecutter-flask/cookiecutter-flask, and am wondering how you would register the flask-socketio extension.
More specifically, what if you create a `socket.py` where all event handlers for flask-socketio are defined?
How can I register this module with my application, so that the app is aware of socketio and listens for events?

**Comment by miguelgrinberg** [comment]
Did you have any specific problems adding Socket.IO to that template? This is a fairly standard Flask app, I don't see why it would not work with Flask-SocketIO.

**Comment by atomtm** [comment]
This is my setup at the moment:
## app.py
```
from flask import Flask
from extensions import socketio


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secretsecret'
    register_extensions(app)
    return app


def register_extensions(app):
    socketio.init_app(app)
    return None


app = create_app()
```
## extensions.py
```
from flask_socketio import SocketIO

socketio = SocketIO()
```
## client.py
```
from flask import request
from extensions import socketio


@socketio.on('test')
def test():
    socketio.emit('test', broadcast=True, include_self=False)
```
## views.py
```
from flask import render_template, send_file
from app import app


@app.route('/')
def index():
    return render_template('index.html')
```
## main.py 
```
from app import app
from extensions import socketio
from views import *
from clients import *

if __name__ == '__main__':
    socketio.run(app, debug=True)
```
Would greatly appreciate your comments on this.

**Comment by miguelgrinberg** [comment]
Does it work? I don't see any problems.

**Comment by atomtm** [comment]
It works yes, however would like your opinion on application structuring. Is the above correct way?
Can it get better ?
I don't really like the way I `import *` from `views` and `clients`.
Also can you please explain the difference of SocketIO() vs SocketIO().init_app() ?

**Comment by miguelgrinberg** [comment]
Well, you are not taking advantage of the application factory pattern much, since you create the app right below the `create_app` function. I would use the style that the cookiecutter pattern uses, and then change `autoapp.py` to something like:

```python
# -*- coding: utf-8 -*-
"""Create an application instance."""
from {{cookiecutter.app_name}}.app import create_app
from extensions import socketio

app = create_app()

if __name__ == '__main__':
    socketio.run()
```

Then you can import your Socket.IO handlers  in app.py and there is no need to use the `import *` pattern which is frown upon. Just do `import client`.

**Comment by atomtm** [comment]
You 're right. I used `create_app()` in `app.py` so that I can import it and use it for `views.py`. If I used the cookiecutter pattern then I should import `app` from somewhere (`main.py` for example) to use it with `app.route()` but this would lead to circular dependencies , or am I missing something?

**Comment by miguelgrinberg** [comment]
Okay, sorry, I did not really look at your http routes, because I assumed you were not interested in my commenting on that. Now that I looked at it, it seems you have ignored the structure set up by the cookiecutter template and implemented your own, much more basic structure. Why are you using the cookiecutter template if you want a simpler approach?

The cookiecutter solution is better, because it is based on blueprints, so there is no need to ever use `@app.route`. But if you prefer the simpler approach that's fine too. But I don't think you need the cookiecutter support if you are going to go that way.

**Comment by atomtm** [comment]
Ok will try the cookiecutter solution and use blueprints. After this I will read your comments again on the subject! 
Really appreciate your help here
