### ISSUE TITLE
Using NATS consumer with flask socketio

### ISSUE THREAD

**Issue by b177y** [miguelgrinberg/Flask-SocketIO#1465]
**Your question**
I am trying to set up a NATS consumer with flask socketio, so that when a message is received from NATS, I can process it and emit a notification to the correct room with socketio. I am aware that the nats.py client uses asyncio, but I am using regular flask which is not async, which may be causing issues. I see that it's possible to use a Redis / RabbitMQ / Kafka message queue with flask socketio so I thought in theory it should be possible to do this with NATS? I've currently tried running my NATS subscribe loop in a socketio start_background_task but I'm not getting any output from the task. Not sure where to look next

**Logs**
Please provide relevant logs from the server and the client. On the server, add the `logger=True` and `engineio_logger=True` arguments to your `SocketIO()` object to get logs dumped on your terminal. The same arguments can be used on the [python-socketio's client](https://github.com/miguelgrinberg/python-socketio). If you are using the JavaScript client, see [here](https://socket.io/docs/logging-and-debugging/) for how to enable logs.

**Comment by miguelgrinberg** [comment]
Flask and asyncio are very difficult to mix in the same process. I don't have any knowledge of NATS so I cannot really give you any specific advice, other than it would be a lot easier to have one process as your NATS client using asyncio, and a separate process for your Flask-SocketIO server.

So then the problem is how these two processes communicate, and here you have a few options:

- Your NATS script can send a request to your Flask server when you need a emit something to a client through Socket.IO. You would have to make sure that this request is private and can only be used by the NATS client, of course. This is I think the easiest option.
- You can use the method described in the Flask-SocketIO documentation for emitting from an external process. The complication here is that you can't use Flask-SocketIO in your asyncio process, so you'll need to use python-socketio instead.
- You can invent your own inter-process communication mechanism using sockets, a queue, etc.

**Comment by b177y** [comment]
Thank you! If I were to use redis as my message streaming system instead of NATs, would it be possible with flask_socketio to process a message when received from redis, and decide which room to emit it to rather than broadcasting it to all clients ( `with SocketIO(app, message_queue='redis://')` ) or would this make more sense / work if I wrote a redis subscriber function (as a synchronous function) and ran it as a background task with `start_background_task` ?

**Comment by miguelgrinberg** [comment]
@b177y The use of Redis by this package is limited for multiple instances of Socket.IO servers or auxiliary emitting processes to communicate. This does not enable your application to use Redis and somehow integrate it with Socket.IO, if you need this type of integration you have to build it as part of your application. Based on what you have described so far I do not understand why you would want to use the `message_queue` argument, that would only make sense if you have multiple Socket.IO processes and that was the only reason I suggested it as an option.

**Comment by b177y** [comment]
Ok, I think I had misunderstood the use of the message queues built into flask_socketio.

I'm also not sure if I'm understanding the start_background_task feature of flask socketio, I have written a redis subscriber function (from which i intend to emit socketio messages to rooms) and I am starting that as a task with `socketio.start_background_task(redis_subscribe)` but this is blocking and I can't access the flask endpoints. Is this expected behaviour or am I missing something to set it up / this isn't the intended usage?

**Comment by miguelgrinberg** [comment]
@b177y are you using eventlet or gevent? If you are, then Redis becomes blocking, you have to monkey patch the Python standard library to use greenlet-friendly networking. Docs: https://eventlet.net/doc/patching.html.

**Comment by b177y** [comment]
Currently using eventlet, thanks I will look into that!
