### ISSUE TITLE
WebSocket with Python (TCP) socket

### ISSUE THREAD

**Issue by pekhaa** [miguelgrinberg/Flask-SocketIO#1468]
I have a Python Flask application which is communicating with an other application running in localhost using tcp socket connection. After changing my app.run to socketio.run my tcp socket communication stops (it only sends the messages upon closing my app). So it seems to be a conflict between regular socket and websocket. Is there any way around this?

**Comment by miguelgrinberg** [comment]
Are you using eventlet or gevent? The conflict between these frameworks and the socket library, this package has nothing to do with it. Either stop using these frameworks, or you may also look into their monkey patching option, which often allows you to use sockets, threading, etc. without causing any blocking.

**Comment by pekhaa** [comment]
Thanks for your prompt response. No, I'm not using either of them, just Werkzeug.

**Comment by miguelgrinberg** [comment]
Can I see the output of `pip freeze`?

**Comment by pekhaa** [comment]
Here:
[pip freeze.txt](https://github.com/miguelgrinberg/Flask-SocketIO/files/5847326/pip.freeze.txt)

**Comment by miguelgrinberg** [comment]
The `app.run` and `socketio.run` functions do more or less the same in your case. Since you are not using eventlet or gevent, the web server is Werkzeug in both cases. So I don't see how changing between these functions can make a difference for your TCP socket code. You mentioned WebSocket above, but Werkzeug does not support WebSocket, your Socket.IO connections are using HTTP, same as Flask routes.

If `app.run()` or `flask run` work better for you, then you can use that. As long as you initialize the Flask-SocketIO extension everything should work.

**Comment by pekhaa** [comment]
Oh yes, you are absolutely right, it works fine if I use app.run. My bad, I was assuming socketio.run is required in order to use Socket.IO... 
Thanks a million!! I was already almost giving up with my project. :)

**Comment by georgegoldman** [comment]
please am having difficulties on building with socket please any clue?
