### ISSUE TITLE
Why does Flask-SocketIO require sticky sessions? (and standard practices)

### ISSUE THREAD

**Issue by Naman-ntc** [miguelgrinberg/Flask-SocketIO#1507]
Hi, 
I was wondering why are sticky sessions required for hosting flask-socketio server. From my understanding, sticky sessions are basically used to route a request to the same server where the session originated. 

1,) (this might be trivial since I am fairly new to backend development) -- why do you need sticky sessions for multiple workers in the same server. Isn't it possible for them to share session information? 

2.) I wanted to confirm - the eventlet flask-socketio server doesn't use multiple workers by default right?

3.) To store the session id's I am using a dictionary in flask app with keys as a random unique id for each client and values as session-id as follows.

```
app = Flask(__name__)
app.clients = {}

# SocketIO
socketio = SocketIO(app)

@socketio.on('connect', namespace='/custom')
def events_connect():
    userid = str(uuid.uuid4())
    session['userid'] = userid
    current_app.clients[userid] = request.sid
    emit('userid', {'userid': userid})
```

Is there a suggested/standard approach to store the room information? I believe this should be thread-safe and should work even if I use multiple workers.

Thanks,

**Comment by miguelgrinberg** [comment]
> 1,) why do you need sticky sessions for multiple workers

Because user session data is kept in memory. All requests from a client need to go to the same server because only that one server keeps the client's state.

Note that if you only allow WebSocket, then this requirement goes away. A WebSocket connection is established with a single request. The sticky sessions are necessary if you want to support the long-polling transport.

> 2.) I wanted to confirm - the eventlet flask-socketio server doesn't use multiple workers by default right?

You are confusing things here. Flask-SocketIO is not have a server, it is a WSGI application, with some extensions to support WebSocket.

Eventlet supports multiple workers, but note that one eventlet worker can handle thousands of clients concurrently, unlike a standard web worker which can handle just one. So the need to use multiple workers when using eventlet or other async frameworks is diminished.

Flask-SocketIO also supports multiple workers, but because this is a stateful application, when using multiple workers you need to provide a mechanism for all the workers to communicate and coordinate. For this you can use a message queue such as Redis or RabbitMQ. All you need to do is provide the service for Flask-SocketIO to use.

> 3.) To store the session id's I am using a dictionary

Why create a random id? Use `request.sid` as your used id instead.

**Comment by Naman-ntc** [comment]
Thanks for such a quick response (that too on a weekend!)

>Note that if you only allow WebSocket, then this requirement goes away...... sticky sessions are necessary if you want to support the long-polling transport
From my understanding WebSocket is an alternative to the long-polling. Why would I want/need to use both options? (I do see some communication in network console with `transport=polling` but I believe that is just normal polling required to upgrade to websocket transport. 

>Eventlet supports multiple workers, but note that one eventlet worker can handle thousands of clients concurrently,
Oh, I wasn't aware of that. Thank you. Btw you mentioned in reply to some issue that people prefer gunicorn over eventlet. Is there any reason for that?

>Why create a random id? Use request.sid as your used id instead.
Right, I was used scripts from an old project which was doing this (it was before `request.sid` was used for room and `request.namespace` used to communicate with client. I should change this now!

**Comment by miguelgrinberg** [comment]
> I do see some communication in network console with transport=polling but I believe that is just normal polling required to upgrade to websocket transport

Right, this is the standard way a Socket.IO connection is made. If you want clients to use this standard way, then you need sticky sessions. If you disable long-polling then you can get away with not setting up the sticky sessions, but you are going to need to tell your clients to connect via WebSocket directly, which is not the default.

> Btw you mentioned in reply to some issue that people prefer gunicorn over eventlet. Is there any reason for that?

Gunicorn is well known and familiar to most people. Eventlet is not.

**Comment by Naman-ntc** [comment]
>you are going to need to tell your clients to connect via WebSocket directly, which is not the default.

In my case, I am building a REST API and also writing client-side js files to use the API. So I can just update transport mode in js from polling to websocket and get rid of sticky sessions right?

Thanks again,

**Comment by miguelgrinberg** [comment]
> So I can just update transport mode in js from polling to websocket and get rid of sticky sessions right?

Yes, that should do it.
