### ISSUE TITLE
How to disable the polling transport?

### ISSUE THREAD

**Issue by JoseGoncalves** [miguelgrinberg/Flask-SocketIO#1559]
**Your question**
Socket.io library has an option to initialize the server for websocket usage only (i.e., to disable the polling transport) via `transports` option. This is described in this link from the Socket.IO's documentation:

https://socket.io/docs/v4/server-initialization/#transports

In a Node.js app I've successfully initialized my server in the following way to disable the Socket.IO's polling transport:

```javascript
const app = require('express')();
const http = require('http').Server(app);
const options = { transports: ['websocket'] };
const io = require('socket.io')(http, options);
```

May I know how can I initialize Flask-SocketIO to disable the polling transport?

**Comment by miguelgrinberg** [comment]
The server does not currently have options to enable or disable transports, both transports are always enabled.

**Comment by JoseGoncalves** [comment]
@miguelgrinberg Would this be something that can be added with some/little effort?

I ask this, because:
1. All currently active browsers support websockets, so it seems a waste of resources/time to start a server using the polling transport and only afterwards to upgrade to the websocket transport.  
2. My Python skills are very limited, so I can not dig into Flask-SocketIO to see were that change can be made.

**Comment by miguelgrinberg** [comment]
I guess it can be done, but I don't really see it as high priority.

There is a single server, shared by polling and websocket transports. Disabling polling would not save any resources. Also, the client is not forced to connect via polling. Socket.IO clients have an option to request a direct connection via websocket and that is supported by this server.

Note that the polling connection step serves a useful purpose, which is to allow the client to authenticate via custom headers. WebSocket connections do not allow custom headers, so in many situations applications use the polling step not because it provides any technical benefit, but only as a vehicle for the client to send a token in a header.

**Comment by JoseGoncalves** [comment]
OK, I understand that the polling transport can be usefull to some applications that require authentication, but there are others which that is not the case, and that would want to use only webscockets.

While this feature is not added to the server, I'lll be using the client config to request a direct websocket connection.

Thank you for the quick reply and clarification.
