### ISSUE TITLE
Is client SSL authentication possible?

### ISSUE THREAD

**Issue by lazercorn** [miguelgrinberg/Flask-SocketIO#1574]
So I know how to start flask socketio with SSL by passing certfile and keyfile as arguments to socket.run()

 but is it possible to do client SSL authentication? like be able to pass a client_certfile and CA_certfile argument to socket.run()?

**Comment by miguelgrinberg** [comment]
@lazercorn Flask-SocketIO is not a web server, so it does not really care about how you configure TLS/SSL. Instead of using `socketio.run()`, run your application directly through your chosen web server, and use the options that you need to configure it. I believe Gunicorn can do this.

And if you need to know how to start a Flask-SocketIO application with Gunicorn, this is covered in the docs.

**Comment by lazercorn** [comment]
Thank you. I will use gunicorn.
