### ISSUE TITLE
Non-Flask based python implementaiton

### ISSUE THREAD

**Issue by nipunarora** [miguelgrinberg/Flask-SocketIO#158]
Can socketio be used with several python clients and javascript clients.
My use-case is as follows. I have a controller (python script), which is sending tasks to several workers in distributed nodes. I would like to send the console output of each worker to the front-end javascript.
I wonder what would be the best way to design this?

**Comment by miguelgrinberg** [comment]
You could run your tasks over a pipe to capture the output, which you can then send to the socketio client as event data.

**Comment by nipunarora** [comment]
What do you mean run over a pipe? Can each worker communicate to a broadcast channel?
Basically:
1. Can a python client be made independent of flask? 
2. Can socketio talk over distributed nodes? I.e. have a central socketio server, and clients on various machines?

**Comment by miguelgrinberg** [comment]
I mean this: https://docs.python.org/2/library/subprocess.html#popen-constructor. This function allows you to start a child process with the stdout and stderr connected to pipes. The parent process can read the output from the child process by reading from a file handle.

> 1. Can a python client to socket.io be made independent of flask? 

Your question is not clear. You can have a socketio server with or without Flask. I suspect what you are asking though, is if a separate process can emit to a Javascript client through the Flask socketio server, correct?

The answer (at this time) is no, only the server can send to the clients, because it owns the socket connections. If a separate process needs to send something, it needs to give it to the server, and then the server can send it.

But if you use popen to start children processes from the server, this is easy. The server can read the output of the children from the pipes and send the data over to the clients.

> 2. Can socketio talk over distributed nodes? I.e. have a central socketio server, and clients on various machines?

This is confusing again, because what you refer as clients are not socketio clients. You want multiple processes to act as the socketio server, all communicating with the clients.

The way this is implemented is by having a these other processes communicate with the server and pass what they need to send to the socketio clients. This is currently not supported by this extension, but I plan to support it using Redis. Once I get this done you will be able to emit to a client simply by posting the message to a Redis channel that the server is watching.

**Comment by ktoh** [comment]
Depending on how many services and clients you have, and what kind of latency you need, you could:

1. Set up a room for each client and have the services join the room. Log events are simply emitted by each service to the room. This is very simple to implement but there is some wasted bandwidth as messages are emitted to the entire room. 

2. Set up the flask-socketio server as aa message router. Each client establishes a connection to the server. Each service establishes a connection with the server. The server maintains a subscription map of which clients are listening to which services. As log messages come in from services, the server emits messages to the listening client(s). 

Python services can emit to flask-socketio just fine. You can use a library like
https://github.com/invisibleroads/socketIO-client

@miguelgrinberg look forward to the redis based message dispatching. This seems like a good step to getting flask-socketio to support distributed socketio servers.

**Comment by miguelgrinberg** [comment]
> Python services can emit to flask-socketio just fine. You can use a library like https://github.com/invisibleroads/socketIO-client

If you use a library like this one, the Python service becomes another client. To the server, the Javascript clients and these Python based ones are the same. You can implement server functionality that allows a client to message another, and that way you can get a Python based service to send an event to a Javascript client, but I'm not really sure this is a good solution. You are still going through the  server, but there are more efficient ways to connect a Python process to the server than using socketio.

**Comment by nipunarora** [comment]
@miguelgrinberg  and @ktoh : Thanks for your suggestions..

Let me first explain my usecase, pehraphs that will make things a little clearer. I have a webserver running, which dispatches "command messages" to workers running in different machines. Now let's say a user inputs a command in the website, the command is forwarded by the webserver to a worker node. I can do all this using a simple redis based message queue. I would also like to show the console output of the command running in the worker thread on the website. For this I wanted to use socket.io.

Something along the lines of http://logio.org/ 

@miguelgrinberg - 

Unfortunately, Popen works only for subcommands within the same machine, so will not be a good option for me. I look forward to your redis extension it looks much cleaner. Unfortunately I need something now. If you have an early/simple version ready, I would love to have a look. Otherwise I am going to try @ktoh 's idea ... 

Can you also tell me which port socket-io runs on, I will need it for the python based socket-io client? I do not see any port configuration for socket-io in the flask-socketio extension (maybe I missed it? )

@ktoh: 

I like the idea. I am going to look into the python client you sent. Thanks for the link!

**Comment by miguelgrinberg** [comment]
@nipunarora if you have a Redis backend by which your server can send commands to the different workers, I think it would be easy for you to implement the reverse, where each worker can send output of commands that execute in that process back to the server. The server, once it has the output, can relay it to the client via the `emit()` function over the Socket.IO protocol.

**Comment by ktoh** [comment]
@nipunarora if you are going with the router-approach I agree with @miguelgrinberg ....it's likely that socketio is not the best approach for the worker-to-server communication (use Redis, Celery or 0MQ instead).  The socket_io server can then emit to the client using socketIO.

If you're going with the room-based approach then yeah it probably is simplest to standardize on socketIO for workers and clients alike.

Good luck
