### ISSUE TITLE
[Missing Docs] Can I deploy it with uwsgi?

### ISSUE THREAD

**Issue by item4** [miguelgrinberg/Flask-SocketIO#168]
Can I deploy it with uwsgi? An other word, Can it run without gunicorn?

I can not find on docs about it.

**Comment by miguelgrinberg** [comment]
I don't think you'll be able to run WebSocket through uwsgi at this point, but you should be able to run the long-polling transport if you configure uwsgi to use the gevent plugin.

Since WebSocket is not part of the WSGI standard, each server supports it in a different way, and uwsgi uses a particularly complex way, with its own implementation of the entire protocol, instead of relying on a Python based implementation such as the one provided with eventlet or gevent-websocket. I have not figured out how to hook up the uwsgi WebSocket support with this extension yet, but I'll keep this issue open as a remind to work on that.

**Comment by miguelgrinberg** [comment]
Documentation on the currently limited support of uWSGI has been added. Closing.

**Comment by liaodalin19903** [comment]
If I use the `eventlet.wsgi.server`: 

```
import eventlet.wsgi
eventlet.wsgi.server(eventlet.listen(('', 8000)), application)
```

Whether when I distribute my application it's ok without uWSGI? whether I can use the `eventlet.wsgi.server` directly?   like this?
