### ISSUE TITLE
Emitting from background thread does not always work

### ISSUE THREAD

**Issue by Schnodderbalken** [miguelgrinberg/Flask-SocketIO#192]
It seems like when using eventlet, flask-socket.io can not deal with messages that are being emitted in the function that handles a request. But only in the case that it is performed in a separate thread and it has some computational intensive stuff going on that takes some time. I have an example:

```python
from flask import Flask
from flask.ext.socketio import SocketIO, emit
app = Flask(__name__)
socketio = SocketIO(app)

from threading import Thread
import time 

@socketio.on('client command')
def response(data):
    thread = Thread(target = testThreadFunction)
    thread.daemon = True
    thread.start()

    emit('client response', ['foo'])

def testThreadFunction():
#   time.sleep(1)
    socketio.emit('client response', ['foo from thread'])

socketio.run(app)
```

If the sleep function is commented the message 'foo from thread' finds its way to the client. If we leave the sleep function (or any other function that takes some time to be computed) there uncommented the message never reaches the client.

I am using Mac OSX 10.10.2, Python 3.4.3, Flask 0.10.1, flask-socketio1.2 and eventlet 0.17.4.

**Comment by miguelgrinberg** [comment]
Very likely the problem is that you haven't monkey patched the Python libraries. When you use eventlet, you basically have two options. One option is to use eventlet's own concurrency and I/O functions, so you would be using `eventlet.sleep` instead of Python's `time.sleep`. Another alternative that is sometimes simpler is to call `eventlet.monkey_patch()` at the top of your application. The monkey patching function goes and replaces several Python functions with the eventlet equivalents. If you monkey patch, you can still call `time.sleep`, but the call will be redirected to `eventlet.sleep` for you.

You also mentioned functions that do long computations. This type of function is basically an enemy of asynchronous web servers. Because eventlet servers run on a cooperative threading model, any thread that uses the CPU for a long time will cause all other threads to starve. If you have a loop in your long calculation, you may want to insert a sleep call, which allows eventlet to do a context switch and give the CPU to other threads that need it.

**Comment by Schnodderbalken** [comment]
Thank you very much for the quick response.
Indeed I hadn't monkey patched the Python libraries.
Although in my case I can't insert sleep calls in between several steps as the long computations happen in a subprocess that gets the input piped in and output piped out. I don't have the possibility to sleep somewhere in the middle of that process.

**Comment by miguelgrinberg** [comment]
If the calculations happen in a subprocess then they are not blocking the main process, so it is not a problem. You just need to monkey patch your main process, so that all the I/O functions that wait on the subprocess do not block. (I think pipes are non blocking with eventlet on most platforms, if it turns out they do block on yours, then it is a problem).

**Comment by Schnodderbalken** [comment]
Okay in any case, this issue can be closed. Thanks again!
