### ISSUE TITLE
Binary data support

### ISSUE THREAD

**Issue by chipsenkbeil** [miguelgrinberg/Flask-SocketIO#195]
Does this project support binary data being sent over SocketIO? The client-side Javascript has support since [1.0](http://socket.io/blog/introducing-socket-io-1-0/#binary), but I cannot tell if this project has any support for binary data (such as blobs).

I've only seen string and json support mentioned. While sending the blob does get me the placeholder for the blob in the resulting json on the server, I don't know if the binary data is received/processed.

I also see that your other project, https://github.com/miguelgrinberg/python-socketio, has support for binary messages.

**Comment by chipsenkbeil** [comment]
Oh, I see there is a binary option I can set for SocketIO. Is that the recommended way? I'll give it a go and close this issue if that seems to work.

**Comment by miguelgrinberg** [comment]
Yes, there is binary support, although to be honest, I haven't done extensive testing on it.

If you are using Python 3, then any components in the data that you emit that are bytes are treated as binary. For example, in the following structure, there is one binary component, while every thing else is treated as JSON: `{'foo': 'bar', 'bin': b'this is binary'}`.

If you using Python 2, then it's complicated, because the distinction between text and bytes is harder to make. By default, in Python 2 everything is treated as text, so you will not be able to use binary. To use binary, pass `binary=True` in the `SocketIO` constructor, and then anything that is str or bytes will be treated as binary, while unicode strings will be treated as text and sent as JSON.

**Comment by cwillforeal** [comment]
Did this get tested?  I'm trying to send a byte array and am getting a TypeError saying the bytearray is not JSON serializable.

**Comment by miguelgrinberg** [comment]
@cwillforeal yes, this has been tested and is in use. On the Python side, you can send binary data as a bytes sequence, or also as a mixed JSON/bytes object such as:

`{"data": b"this is a binary blob"}`

**Comment by chinnaxs** [comment]
> Did this get tested? I'm trying to send a byte array and am getting a TypeError saying the bytearray is not JSON serializable.

I also have trouble directly putting a 'bytes' object into 'emit' as parameter.
```
            msg = bytes.fromhex('deadbeef')
            self.sio.emit('bytes',msg)
```
TypeError: Object of type 'bytes' is not JSON serializable

Even though the [documentation](https://python-socketio.readthedocs.io/en/latest/) says it should be possible?
`The single argument provided to the method is the data that is passed on to the server. The data can be of type str, bytes, dict or list. The data included inside dictionaries and lists is also constrained to these types.`
Using: 
python-socketio==3.1.2
socketIO-client==0.7.2
