### ISSUE TITLE
What's the best way to persist/retrieve a client sid from Flask?

### ISSUE THREAD

**Issue by dimitrovs** [miguelgrinberg/Flask-SocketIO#198]
In my application a client logs in using Flask-Security. Then it connects over Socket.io . What is the best way to store the request.sid value such that Flask can find it later and send messages only to this specific user?

For instance, assume a client initiates a long running operation over HTTP. Then a backend server calls Flask with the result of the operation (over HTTP). I want Flask to find the sid of the user who initiated the operation and to send a message over socket.io . I am thinking one way is to add the sid to the User model and persist it in the DB. Another approach is to create a user <-> sid global mapping in Flask.

What would you suggest as the best approach?

**Comment by miguelgrinberg** [comment]
The safest bet is to write the sid to your database, or if you prefer something faster to a key/value store such as redis.

You can also build a mapping from username to sid in memory, but one limitation with that approach is that if you ever scale your service to have multiple workers, then the memory approach will break. You are safe now, because Flask-SocketIO does not support multiple workers anyway, but I'm adding this feature in the next release.

**Comment by dimitrovs** [comment]
Thanks. I did it with storing in DB.
