### ISSUE TITLE
Flask-SocketIO with Beaker sessions

### ISSUE THREAD

**Issue by Grant1219** [miguelgrinberg/Flask-SocketIO#224]
I have been using Flask-SocketIO with great success along with Beaker sessions to share session state between a Pyramid application and websocket connections.

When I tried upgrading from Flask-SocketIO 1.1 to 2.0 I ran into the following error:

```
Traceback (most recent call last):
  File "vm_runner.py", line 5, in <module>
    sockio.run(app, host = app.config['HOST'], port = app.config['PORT'], debug = app.config['DEBUG'])
  File "/srv/tradewind/dev_venv/local/lib/python2.7/site-packages/Flask_SocketIO-2.0-py2.7.egg/flask_socketio/__init__.py", line 379, in run
    flask_app.wsgi_app = DebuggedApplication(flask_app.wsgi_app,
AttributeError: 'SessionMiddleware' object has no attribute 'wsgi_app'
```

Obviously this is because Beaker does not provide a wsgi_app, but is this a problem with Beaker? Or is this a problem with the way I am attaching middleware?

Here is my Flask and middleware initialization code:

```
app = Flask('tradewind_realtime')
app.config.from_object('tradewind_realtime.default_settings')
app.config.from_envvar('TRADEWIND_REALTIME_SETTINGS', silent=True)

session_opts = {
    'session.type':     app.config['BEAKER_SESSION_TYPE'],
    'session.url':      app.config['BEAKER_SESSION_URL'],
    'session.key':      app.config['BEAKER_SESSION_KEY'],
    'session.timeout':  app.config['BEAKER_SESSION_TIMEOUT']
}

sockio = SocketIO(app)
app.wsgi_app = SessionMiddleware(app.wsgi_app, session_opts)
app.session_interface = BeakerSessionInterface()
```

Then later on:

`sockio.run(app, host = app.config['HOST'], port = app.config['PORT'], debug = app.config['DEBUG'])`

Let me know if I'm doing something wrong. I am sticking to Flask-SocketIO 1.1 for now, but I will dig deeper into this issue soon hopefully.

**Comment by miguelgrinberg** [comment]
Yeah, I think I see what the problem is. Flask-SocketIO makes the (possibly wrong) assumption that it has the last middleware applied to the app object. The Flask-SocketIO middleware acts as a router, it takes all requests, inspects them, and passes Socket.IO requests to the extension's Socket.IO handling code, while passing through all other requests to the Flask WSGI application.

You are putting the `SessionMiddleware` on top of Flask-SocketIO, and because of that the routing mechanism breaks in the Flask-SocketIO middleware breaks, now Flask-SocketIO is unable to properly route requests.

I think this is something I should improve, but I have to think about how to do that. In the meantime, if you move your `SocketIO(app)` call after you add all other middlewares, then the error you are getting will go away, I think.

**Comment by Grant1219** [comment]
The application does run when SocketIO is applied as the last middleware, but then you run into the issue where SocketIO requests no longer have access to the environ['beaker.session'] key since that middleware comes after SocketIO.

It also should be noted that this exception only happens when debug is set to True, otherwise it runs fine.

Would it break something if the following code was changed?
```
diff --git a/flask_socketio/__init__.py b/flask_socketio/__init__.py
index 7687b81..2dd4797 100644
--- a/flask_socketio/__init__.py
+++ b/flask_socketio/__init__.py
@@ -375,7 +375,7 @@ class SocketIO(object):
             # constructor.
             # app.wsgi_app.wsgi_app is the wsgi_app from the Flask application
             # instance
-            flask_app = app.wsgi_app
+            flask_app = app
             flask_app.wsgi_app = DebuggedApplication(flask_app.wsgi_app,
                                                      evalex=True)
```
This fixes the problem for me, but I suppose the issue could come up again if app.wsgi_app also doesn't exist.

**Comment by miguelgrinberg** [comment]
@Grant1219 My main concern is that WebSocket does not really fit the WSGI model, so putting a WSGI middleware in front of Flask-SocketIO may not work in the way one would expect.

For example, with the beaker sessions, it's unclear to me that sessions that are modified in socket handlers will ever get saved. Looking at `SessionMiddleware`, the technique it uses to get the sesson saved is to intercept the call to `start_response`, which is issued to output the response headers. Because when you are using WebSocket there is no response, this will never happen, so without thinking into it too much, my impression is that your sessions will never get saved unless you manually save them.

Second to that, the change you've made works in the general case, but you are basically mounting the Werkzeug debugger middleware on top of the Flask-SocketIO middleware. This can cause weird dynamics when there are failures in the socket routes. I don't know what can happen if the debugger middleware catches an exception that is coming not from the WSGI side but from the WebSocket side, but it is certainly not going to be good.

So yeah, I understand the problem, and I agree it would be ideal that it is fixed from the Flask-SocketIO side, but I think the solution is going to be a bit more complex.

**Comment by Grant1219** [comment]
Yea I do understand that changes made to sessions will not be saved. I am strictly using Beaker as a way to read session data.

WebSocket doesn't fit the WSGI model, but there are many reasons why a WebSocket connection may need to access session data. Would you suggest dropping the middleware altogether and using Beaker's Session class directly within SocketIO? That is an option, but it would add code to each route in order to retrieve the session.

Another viable solution could be to inherit from SessionMiddleware and create a ReadOnlySessionMiddleware class. I only prefer middleware because it exposes the session data right in the request context without extra code per route.

Thanks for discussing this with me.

**Comment by miguelgrinberg** [comment]
> WebSocket doesn't fit the WSGI model, but there are many reasons why a WebSocket connection may need to access session data

Absolutely, that's not in discussion. Note that the problem with session saving is not particular to beaker, when using regular Flask sessions there are some limitations as well, which I list in the documentation.

> Another viable solution could be to inherit from SessionMiddleware and create a ReadOnlySessionMiddleware class

I personally don't think this is necessary, and would complicate things because you will want sessions to get saved when you get into HTTP routes. You need a smarter middleware that can save the session when possible, but guess what, that is exactly how the current `SessionMiddleware` is working for you. If you understand the limitations, then you are fine.

So I'm thinking your usage of beaker sessions is fine. What's not fine is the strategy I use to add the debugger middleware, which assumes Flask-SocketIO's middleware is the last one. Basically, the current assumption is that you have the following middleware chain:

                    mw1   mw2   mw3   Flask app
                     o ---- o ---- o ---- o
                    /
                   o Flask-SocketIO
                    \  middleware
                     o
                  Flask-SocketIO WebSocket handler

Where mw1, mw2 and mw3 are any WSGI middlewares. And then if you enable debug mode, I alter the change as follows:

                  dbg-mw   mw1   mw2   mw3   Flask app
                     o ---- o ---- o ---- o ---- o
                    /
                   o Flask-SocketIO
                    \  middleware
                     o
                  Flask-SocketIO WebSocket handler

Your setup looks like this:

                    mw1   mw2   mw3   Flask app
                     o ---- o ---- o ---- o
          bkr-mw    /
            o ---- o Flask-SocketIO
                    \  middleware
                     o
                  Flask-SocketIO WebSocket handler

What I need to find, is a way to insert the debugger middleware in the correct place, in spite of having a Beaker middleware at the head of the chain:

                  dbg-mw   mw1   mw2   mw3   Flask app
                     o ---- o ---- o ---- o ---- o
          bkr-mw    /
            o ---- o Flask-SocketIO
                    \  middleware
                     o
                  Flask-SocketIO WebSocket handler

I think one way to achieve this would be by saving the Flask-SocketIO middleware in the `SocketIO` object, so that I don't need to look at the WSGI middleware chain to find it.
