### ISSUE TITLE
Retrieving all connected sockets?

### ISSUE THREAD

**Issue by faxdata** [miguelgrinberg/Flask-SocketIO#240]
Hi!

Great work with this!

Is there a way to iterate through all connected sockets and pull current_user? 
I use Flask-Login together with Flask-SocketIO and I need a way to see if a user is signed in with both desktop and mobile device. When a user disconnects I want them to be marked as "offline" in the application, but I can't figure out how to see if user is still connected with another device.

Big thanks!

**Comment by faxdata** [comment]
Did a bit of thinking and found out I can build an array of user ID:s to check against using the on('connect')! Problem solved! ;)

**Comment by miguelgrinberg** [comment]
Right. This is hard for Flask-SocketIO to do, but for the application it should be easy if you keep track of how many socketio sessions are associated with a given username.

**Comment by etcsayeghr** [comment]
Miguel, this would work in a single application setting, but if you are hoping to run multiple workers and one of the workers crashes unexpectedly, we cant expect the disconnect event to occur. Do you have any suggestions for keeping track of connected users across multiple workers?

**Comment by miguelgrinberg** [comment]
Well, not sure if this will work for you, but the socketio client has reconnection logic. If one of the server workers crashes, then all the clients connected to that server will reconnect. If your application does not support multiple connections for a given client, then receiving a connection request for a client that has a known connection effectively means that the previous connection dropped.

**Comment by etcsayeghr** [comment]
Hey Miguel, thanks for the extremely quick response. What if we want to allow multiple connections from the same user (say if they are in multiple tabs)? Right now I am using redis to store a count of how many active connections a user has, and decrementing it everytime they close a connection. Any advice for that situation?

**Comment by miguelgrinberg** [comment]
if you really need to know the connection status of all your clients, and you do not trust the connect/disconnect events, then you have to implement your own testing of each connection. Send a ping message and expect a pong reply within X seconds. If the exchange doesn't happen for a client, then consider that client gone. That is exactly what the server does, by the way.

**Comment by etcsayeghr** [comment]
How do you get a list of connections across workers?

**Comment by miguelgrinberg** [comment]
I don't need to have a list of connections.

**Comment by etcsayeghr** [comment]
How would you know which connections to send a ping to then?

Alternatively, Is there a way to get a list of SIDs that are subscribed to a room?

**Comment by miguelgrinberg** [comment]
Each server maintains its own connections, I don't need to have a complete list. I also cannot give you a list of SIDs in a room, because these could be spread across multiple servers.

**Comment by etcsayeghr** [comment]
How would you send a ping to a user if you dont know which worker(s) has(have) an active connection to it?

**Comment by miguelgrinberg** [comment]
The client sends the ping. The load balancer knows which server handles each client.

**Comment by etcsayeghr** [comment]
Okay, thanks.

**Comment by gordol** [comment]
Hello @etcsayeghr I have done a vaguely similar thing, and thought this pattern might be helpful for you... Sorry if some of the logic is redundant, this originally had a lot more in it, but I stripped it down as an example for you. The way it is so simplified now, you could probably take this and refactor it a bit to make it better, so you can deduce the namespace and action from the wrapped function instead of passing them in as parameters to the decorator... just be sure to move the decorator up, so it's wrapping the socketio method, if you do that.

There is likely a better way to get the session ID then, too, if you wrap the whole thing, socketio method and all, instead of just the connect/disconnect callback. 

Additionally, this could easily be extended to work with multiple backend servers/workers by utilizing a message queue instead of the active_users dict in memory.

If you're worried about worker crashes and no disconnect events firing, then you can simply set an expiration for each user record in your message queue of choice, and then poke it occasionally if the client is active to prevent it from timing out. Then you'll want to alter the decorator to write to the message queue instead of emitting the data directly. Finally, you could then subscribe to and broadcast updates from the queue on each server instance.

Basically, SocketIO is just a protocol, if you want more features you need to build them.

```python
@socketio.on('connect', namespace='/test')
@connected_users_hook('test', 'connect')
def test_connect():
    print(str(datetime.now())+' - Test: client connected')
    emit('response', 'Connected')

@socketio.on('disconnect', namespace='/test')
@connected_users_hook('test', 'disconnect')
def test_disconnect():
    print(str(datetime.now())+' - Test: client disconnected')
```

```python
from flask import request
from flask.ext.login import current_user
import functools
from lib.socketio import emit

active_users = { 'namespace': [], 'other_namespace': [], 'test': []}

def user_or_anon():
    if current_user.is_anonymous():
        return 'anonymous'
    else:
        return current_user.username

def connected_users_hook(section, action):
    def real_connected_users_hook(f):
        @functools.wraps(f)
        def wrapped(*args, **kwargs):
            username = user_or_anon()
            sessionid = request.path.rsplit('/', 1)[1]

            if action == 'connect':
                active_users[section].append({'username': str(username), 'session': sessionid})
                emit('user_connected', {'message': '%s connected' % str(username), 'active_users': active_users[section]}, broadcast=True, namespace='/%s' % section)

            elif action == 'disconnect':
                for idx, user in enumerate(active_users[section]):
                    if user['session'] == sessionid:
                        active_users[section].pop(idx)
                        break
                emit('user_disconnected', {'message': '%s disconnected' % str(username), 'active_users': active_users[section]}, broadcast=True, namespace='/%s' % section)

            return f(*args, **kwargs)
        return wrapped
    return real_connected_users_hook

```

**Comment by miguelgrinberg** [comment]
@gordol pretty interesting example. What's not to love when you implement functionality in a decorator? ;-)

Note that to get the session ID you can just do `request.sid`, you do not need to parse the request URL.

**Comment by gordol** [comment]
Noted :+1: 

I used an older version of the library that I had laying around from an old project when I tacked this out, I didn't even think to update it to the latest version for this example. The old one doesn't have sid attribute on request object, since it was added here, in July 2015: https://github.com/miguelgrinberg/Flask-SocketIO/commit/8591ef4bb373fa0b2535b8d3065d90cc4050650f

One could indeed update this to use request.sid, but it would only work if you move the connected_users decorator above the socketio one, and make a few other tweaks too.

Anyway, just thought the decorator pattern might be useful here. Best of luck @etcsayeghr & @faxdata

**Comment by zsiegel92** [comment]
@miguelgrinberg I'm confused by this interaction. In several other resources, I've seen you recommend not to use any process-specific, thread-specific, server-specific data structure or even method for getting all users from (some or all) rooms, or for all rooms associated with a given user.

Here @gordol is using a global variable, and I'm surprised your response wasn't "use an external database".

For any future users seeing this thread, see [this StackOverflow question about variables outside of contexts](https://stackoverflow.com/questions/32815451/are-global-variables-thread-safe-in-flask-how-do-i-share-data-between-requests).

**Comment by gordol** [comment]
The example you gave is bad because it's mutating a copy of state in parallel and expecting linear results. It's nonsense... Incrementing a counter in parallel is not the same as add/removing unique keys from an array in parallel.

The point is moot, however, because I said you should place that into a message queue like redis instead of the local dict. Thec local dict was for brevity and sake of example.

> Additionally, this could easily be extended to work with multiple backend servers/workers by utilizing a message queue instead of the active_users dict in memory.

> Then you'll want to alter the decorator to write to the message queue instead of emitting the data directly. Finally, you could then subscribe to and broadcast updates from the queue on each server instance.

With the in memory dict, there is no necessary expectation that one process knows all the users, it just knows the ones it's serving.

Python/Flask SocketIO uses green threads by the way... That's not the same as normal threading.. Still doesn't matter though, you should use a message queue if you have users spread across multiple workers.

**Comment by miguelgrinberg** [comment]
@zsiegel92 This isn't as black and white as you paint it. There are many solutions that work well with in-memory structures. There is also a big difference between using global variables in a multithreaded and/or multiprocess application versus a single-instance greenlet application, where the context switch mechanism is completely different.

**Comment by zsiegel92** [comment]
@miguelgrinberg @gordol than you for the responses! To be more clear, I did not intend to answer a question, but I myself am confused about when I might be able to use an in-memory data structure in my flask code like we see here. I’m afraid I still don’t understand when it’d be appropriate.

I am working on a small socket.io app (using Flask-SocketIO), and I will likely launch it on a single heroku dyno, and I’m trying to pull it off with no database. Is a python list or dict defined outside my view/socket.on functions an acceptable place to store some data between requests/emissions?

Thank you so much!
