### ISSUE TITLE
Pure Python client with Flask-SocketIO

### ISSUE THREAD

**Issue by Pr0x1m4** [miguelgrinberg/Flask-SocketIO#270]
Im following your [tutorial](http://blog.miguelgrinberg.com/post/easy-websockets-with-flask-and-gevent), I cloned your repo and have the websocket server up and running, however I intend to build a the websocket client with python instead of javascript using this library [websocket-client](https://github.com/liris/websocket-client). Here's the client file (client)[https://github.com/Pr0x1m4/infosetd/blob/master/infosetd.py].

I can't seem to get the connection to work, whenever I run the client, I get this output
![2016-06-14-133122_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4820517/16054930/e29764b4-3234-11e6-9dec-dac0543d0242.png)

My question would then be can these two libraries work together or what am I doing wrong?

**Comment by miguelgrinberg** [comment]
Flask-SocketIO is not a WebSocket server, it is a Socket.IO server. The client that you need to use needs to understand the Socket.IO protocol, a WebSocket client alone is not enough.

**Comment by Pr0x1m4** [comment]
Oh okay, much appreciated, thanks for clarification.

**Comment by skortchmark9** [comment]
@Pr0x1m4 You might try this: https://pypi.python.org/pypi/socketIO-client

**Comment by maxkoryukov** [comment]
the problem is Google. I was searching `flask websocket` and got the link to this repo on the first page of results. But this project is not about **WEBSOCKET**, it works just with **socket.io**...

Also, I found kennethreitz/flask-sockets#1 - it works good with pure **WebSocket**.

May be it makes sense to add the line  `this project DO NOT work with pure WebSocket` to the top of `README.md` file???

**Comment by MrJaysa** [comment]
please how can i create a pure python client
