### ISSUE TITLE
socketio.on('disconnect') not firing right away (2-5 minute delay)

### ISSUE THREAD

**Issue by MikeSperone** [miguelgrinberg/Flask-SocketIO#291]
Hello!

I started using this library from a youtube tutorial, and it's great so far, but I'm noticing the disconnect event isn't working.  At first I thought it wasn't firing at all, but then later (like 3-5 minutes+) - after refreshing a bunch, and trying opening many tabs and closing them - I noticed my server starting to print out "Client disconnected" as it should do when it disconnects.  The 'connect' event fires and runs immediately every time and has never not worked.  

I'm noticing now that it is a large delay.  Which I suppose I could work with, but the tutorial clearly shows it working immediately with what seems to be about 100 users logging in/out and refreshing VERY quickly... and it appears to be 100% responsive and immediate.  I'm wondering if this is a bug, related to another bug, or if I'm just plain doing it wrong

here is my (simple) disconnect code:
@socketio.on('disconnect')
def ws_disconn():
    print 'Client disconnected'

**Comment by miguelgrinberg** [comment]
There are two communication transports: long-polling and websocket. For websocket, when a client disconnects the server finds out immediately, because there is a dedicated connection that breaks, so it is easy to detect. For long-polling it is not possible, because the communication happens over many connections that are constantly created and going away, so the only way to detect a disconnection is to wait for certain amount of time and if no messages from the client are received in that time then the client is declared disconnected.
