### ISSUE TITLE
Scaling with nginx and sticky sessions

### ISSUE THREAD

**Issue by rohanbabu** [miguelgrinberg/Flask-SocketIO#292]
Hi Miguel, I watched the video of your talk at PyCon 2016 on 'Flask at Scale'. You talked about Socket.IO being a stateful protocol and therefore needing to configure nginx (or any other reverse proxy) to use sticky sessions when running multiple Flask-Socket.IO servers. I have the following questions/concerns about using sticky sessions:
1. Since each server holds a subset of the client connections, If one of the servers fail, is there anyway to have auto failover and have another server take over the connections seamlessly without the clients needing to reconnect or re-login?
2. What happens if a client's IP changes during a session? Will it cause a problem when using nginx with ip_hash? If so, can you suggest any alternatives?

Thanks for this great project and all the tutorials. I hope you find the time to respond to my questions. Cheers!

**Comment by miguelgrinberg** [comment]
1. If a server goes down, all the connections it was handling go down with it. The clients will get disconnected. But Socket.IO clients have reconnect logic, as that is part of the protocol specification. So they will reconnect right after the problem occurs. I agree this is inconvenient, but you have to design your app so that it can handle this situation. One possibility is to store client data in shared storage, such as redis or memcache, so then upon reconnection the client can recover its state.

2. an IP address change can be a problem for long-polling, because requests come and go constantly when using that transport. Websocket is not a problem because once a connection is established it stays on without any need to for the load balancer to be involved. In the long-polling case, I suspect a change of IP address could send requests to another host, and that other host will respond with a 400 error as it does not know the client. That will trigger a disconnect, and as above, the client will then reconnect.
