### ISSUE TITLE
Multiple Flask-socketio instances. 

### ISSUE THREAD

**Issue by ybegator** [miguelgrinberg/Flask-SocketIO#307]
I'm working on an application that broadcasts data (~256 integer numbers per second) from one clients to other via websockets. So there are few input streams of data and few output streams that my application serves being run on a single machine and using flask-socketio. Is it a proper solution to run multiple instances of flask-socketio in separate processes, each of which would handle one input or output stream? Processes can communicate with each other using a zeromq message queue.

**Comment by miguelgrinberg** [comment]
A single Flask-SocketIO server can handle many client connections due to its async nature when you use eventlet or gevent. How many clients do you have?

**Comment by ybegator** [comment]
Somthing over 200 clients. The idea was to make one instance of FlaskSocketIO to serve one port, assuming that internet bandwidth and possibilities of multicore CPU will be used on a maximum (I'm a newbie in web, so correct me, if I misunderstand something)

**Comment by miguelgrinberg** [comment]
Depending on how much traffic there is between these 200 clients, it may be quite possible that a single server can handle it just fine. But if that were not enough, then you can run multiple servers, which will be behind a load balancer such as nginx. The servers will coordinate efforts by communicating over a message queue such as RabbitMQ or Redis. Running multiple servers is a good way to make use of all your available CPU cores, as you suggest, but since the set up is a more complex, I would only go that route if a single server is not able to keep up.

**Comment by ybegator** [comment]
Thank you for your answer! Seems It's time to learn load balansing.

**Comment by miguelgrinberg** [comment]
I hosted a tutorial at PyCon earlier this year in which I discussed how to set things up for Flask, Flask-SocketIO, nginx, a message queue, etc. This may give you some ideas and sample code: https://www.youtube.com/watch?v=tdIIJuPh3SI
