### ISSUE TITLE
Queues without consumers accumulating messages

### ISSUE THREAD

**Issue by MarcDufresne** [miguelgrinberg/Flask-SocketIO#324]
Hi, I've been using Flask-SocketIO for a little while now and I just moved to having multiple workers behind a Nginx proxy. Works great, but I'm having one "issue".

On my RabbitMQ management interface, I can see a lot of seemingly abandoned queues, they are accumulating messages (over 6.9M messages since 5 days ago, but our app is heavy on messages), they are bound to the channel I set in the `init_app` but have no consumer. I traced them back to the client queues used by Flask-SocketIO (this line `queue = kombu.Queue(str(uuid.uuid4()), exchange)` in the `kombu_manager.py`). 

Now I'm wondering why they are there. Did I forget to close a connection (though I didn't see any mention of explicitly closing connections in the doc)?

Now to explain a bit how our app works. We have the workers that are created as such (all following code examples are from the same file):
```python
from flask import Flask
from eventlet.patcher import monkey_patch

EVENTS_CHANNEL = 'events'
monkey_patch()
socketio = SocketIO()

broker = kombu.Connection(config.EVENT_URL, heartbeat=config.MQ_HEARTBEAT)
exchange = kombu.Exchange(config.EVENT_EXCHANGE, type='topic')
_consumers = {}
...
def run():
    ...
    app = Flask(__name__)
    socketio.init_app(app, message_queue='amqp://user:pass@host:port/', channel=EVENTS_CHANNEL)
    ...
    socketio.run(app, host=host, port=port, debug=False, use_reloader=False, log_output=False)

if __name__ == '__main__':
    run()
```

Those workers are listening to a RabbitMQ queue and as they receive messages they send them to Socket.IO using `emit` as such:
```python
def _broadcast_update(payload, room, namespace):
    ....
    socketio.emit('event_name', payload, room=room, namespace=namespace)
```

We're using a subclass of `ConsumerMixin` from kombu and spawning the `run` function of this class with eventlet like so:
```python
def _create_consumer_and_join_room(room, queue_name, subject,
                                   event_name='event_name',
                                   endpoint='/updates'):
    if room not in _consumers:
        def check_event_queue():
            EventConsumer(
                broker, name=queue_name, subject=subject,
                event_name=event_name, ws_endpoint=endpoint).run()

        _consumers[room] = eventlet.spawn(check_event_queue)

    join_room(room)
``` 

We also have another Flask app that runs from the same project (different entry point) that we use to send messages to Socket.IO as well. We have this function in the same file as the above examples that goes like this:
```python
def publish_message(room, payload, namespace):
    sio = SocketIO(message_queue='amqp://user:pass@host:port/', channel=EVENTS_CHANNEL)
    sio.emit('event_name', payload, room=room, namespace=namespace)
```
I followed the example from the documentation that said to initialize a SocketIO instance without an app with the same message queue config and the same channel. Maybe it's this connection that stays alive (the `sio`) or there's a new one getting created each time? This could cause all those queues to appear.

I attached a picture of what my RabbitMQ management interface looks like right now. As you can see I have a lot of queues (1131 and counting) and they all look like this.

![screen shot 2016-09-12 at 4 30 59 pm](https://cloud.githubusercontent.com/assets/599102/18451851/9788b072-7906-11e6-974b-ae064d0b242d.png)

Our networking setup might have something do do with that as well, here are the details of how a connection is made to Socket.IO and Socket.IO to RabbitMQ:
```
Client connection:
JS Client -> HAProxy (w/ source balancing) -> Nginx (w/ `ip_hash`) -> Socket.IO server
```
```
Connection to message queue:
Socket.IO server -> HAProxy -> RabbitMQ
```
Maybe the HAProxy has something to do with all that since the connections "look like" they are coming from the same place and not the Socket.IO servers themselves... (not convinced that this is an issue though)

Now with all that, my apps are working as intended, I can get messages from RabbitMQ, send them to Socket.IO and I can also send them from another process without any problem.
The only issue is the increasing number of queues full of messages.

Any help would be appreciated and if you need additional details just ask. and I'll be glad to provide them.

**Comment by gordol** [comment]
This smells kinda similar to my issue, but we're using Redis... for what it's worth. Eventually Redis runs out of available client slots as a result, and I have to go in and manually kill our socket workers to release the idle connections to redis. Maybe it's a different issue though... Hmm...

**Comment by miguelgrinberg** [comment]
@MarcDufresne it looks like you are constantly creating and discarding `SocketIO` instances. Each one of these will create two RabbitMQ queues, which are currently not destroyed when the `SocketIO` object is garbage collected. The usage that I envision for these object was that they would live through the application, so each process would have only one, and consequently own two queues. I think it would be more efficient to move the `SocketIO` object that you create in function `publish_message` outside, so that it is reused in that process.

I also need to consider destroying the queues when when the `SocketIO` object goes away.

**Comment by MarcDufresne** [comment]
Thanks for the reply! I had actually assumed that the connection would get closed once the Socket.IO instance was discarded, good to know it isn't so at the moment. I will instantiate a single Socket.IO client across my app and see if it helps, I will update this issue later with the result. 
I propose to add a mention in the documentation about the intended usage of the client, maybe that would help people not do what I did.

**Comment by miguelgrinberg** [comment]
Yes, I need to make that more clear in the documentation. I actually have a fully working example of this that you may want to review: https://github.com/miguelgrinberg/flack.

And I'm also going to clean up the queues if the object ever goes away. This isn't a fool proof solution because the process can be killed and then there is nothing I can do to clean up those queues, but at least in the general case of the object getting garbage collected I can do the proper clean up.

**Comment by MarcDufresne** [comment]
So I implemented the change, and I now have one global Socket.IO client that I reuse across the application. It has reduced the number of queues and messages at least for now. Like you mentioned since Flask-SocketIO doesn't clean the queues I still have a bunch of queues that are left over when I restart the app, etc.

Did you think about implementing a public API to clean the connection? It would be great to be able to catch the KeyboardInterrupt (or anything that happens when the app gets killed/restarted) and just call the cleanup function of Flask-SocketIO.

Thanks again for this great extension! Looking forward to future improvements.

**Comment by miguelgrinberg** [comment]
What I'm trying to do is to set a [TTL](https://www.rabbitmq.com/ttl.html) on all queues, so that they go away on their own after they are unused for an amount of time. Unfortunately I do not see a clear way to pass a TTL to a queue through the Kombu package I'm using, I need to investigate how that can be done.

**Comment by miguelgrinberg** [comment]
@MarcDufresne Can I ask you to test a potential fix for this condition?

You will need to install package python-socketio from git master to get this fix. With this package, queues should be auto-deleted after they are inactive for 5 minutes.

**Comment by MarcDufresne** [comment]
Yes, I can test it, it's probably going to take a couple days, though.

Do you think there could be issues if I try to reuse the queue after it has been deleted? Will a new one be created?

**Comment by miguelgrinberg** [comment]
@MarcDufresne I have never used the TTL options before, but my impression when I tested this last night was that as long as the queue is open it does not get deleted. I will do some more testing on this, maybe it is not a bad idea to add the logic you describe, where if I find that a queue was removed I just make another one.

**Comment by MarcDufresne** [comment]
It makes sense that queue remains active while there is a connection. I read "inactive" as a queue with no message going through but the way you describe makes more sense. Now, hopefully, it works like you said.

**Comment by miguelgrinberg** [comment]
I spent some more time with this and made some more improvements.

With release 1.6.0 of package python-socketio, the usage of queues has been greatly reduced. In this version, there is only one queue used per server process. I have also added a `flask-socketio` prefix to these queues, to help identifying them. These queues have the 5 minute expiration time. I have verified that while the server process is running the expiration does not apply. The reason is that one of the conditions for the expiration timer to start running is that the queue should not have any consumers. These server processes are constantly listening and waiting to immediately consume any messages that appear on the queue.

The auxiliary processes that emit through the message queue do not create queues anymore. I did not realize this before, but these do not need a full fledged queue to emit, they only need a producer, which is much more lightweight and emits directly to the exchange.

Please when you get a chance give python-socketio 1.6.0 a try and let me know if there are any other issues.

**Comment by MarcDufresne** [comment]
Thanks! I'll change that in our project and will update you later.
