### ISSUE TITLE
Using nginx as a WebSocket Reverse Proxy with multiple worker hosts

### ISSUE THREAD

**Issue by VincentRichard555** [miguelgrinberg/Flask-SocketIO#332]
I am trying to set up a nginx with socketio using multiple worker hosts. I see that there are some sparse examples here:

https://flask-socketio.readthedocs.io/en/latest/

Is there a more extensive code example on this topic? 

Thanks

**Comment by miguelgrinberg** [comment]
Running multiple workers only requires a minimal code change to configure a message queue. As explained in the documentation, you have to run a message queue (typically redis or rabbitmq), and then add `message_queue=<url>` to the `SocketIO` constructor. Then you can run multiple servers, and configure nginx to load balance them as usual.

**Comment by w-A-L-L-e** [comment]
Yes multiple workers on the same machine. But what is the solution when these workers are split on two physical servers with a seperate ip address? I just e-mailed the issue we see here in our setup we have 2 amazon servers running flask socketio and nginx+sticky sessions manage the load balancing to these 2. In practice during testing we see that a group of users connected to server A don't see the messages typed by users connected to server B.

In other words when users in a chatroom are spread over 2 servers they need to signal eachother with added api calls in order to be able to do the socketio emit properly to all users.
'''
   for s in user.user_sockets:
        #send all users a message
        socketio.emit('updated_model', {'class': 'Message', 'model': {'text':msg, 'html':msg, 'user_id':1} }, room=s.sid)
''''
Above only works for users connected to same server when doing this for loop. In order to get users from the other server also to receive this message we need to add a seperate call to let this server know he also needs to do the socketio.emit's.

Unless we missed something, this seems to be an overlooked detail that is not straightforward to fix nor does it make the code 'just work' regardless of how many hardware servers there are... For regular api calls scaling is pretty easy but for  websockets we see quite some bookkeeping/boiler plate code is missing to make this transparent...

**Comment by miguelgrinberg** [comment]
@w-A-L-L-e are you running a message queue?

**Comment by w-A-L-L-e** [comment]
Yes redis. But currently we have a redis per hardware server. You think it will magically work if we use 1 redis and connect our 2 servers to the same redis? I'm just wondering that part where we do this in events.py: 
```
#this uses socketio.emit (broadcast to all clients)

def push_model(model):
    """Push the model to all connected Socket.IO clients."""
    socketio.emit('updated_model', {'class': model.__class__.__name__,
                                    'model': model.to_dict()})

```

How will both servers do this if only 1 worker is posting a message (or in other words I dont see the @celery.task where we post a message be able to currently signal the other server where other users are connected to also do the push_model and hence socketio.emit...).

**Comment by miguelgrinberg** [comment]
> You think it will magically work if we use 1 redis and connect our 2 servers to the same redis?

Not magically, but yes, it will work. :)

**Comment by w-A-L-L-e** [comment]
So your saying that socketio.emit will cause both servers with seperate ip's to both emit to all their available connected sockets? And then the other one if you do a private message to a specific sid, we do room=sid in the emit call. Will that be intelligent in the sence that if the socket of receiving user is on the other hardware server that this one picks it up and does the websocket push instead of the originating one? Will let you know if it works here (would be awesome!).

**Comment by miguelgrinberg** [comment]
Celery has nothing to do with Socket.IO. If you want to have two sets of celery workers each connected to its own server, through its own redis instance, that's totally fine. It has no relation to Flask-SocketIO.

The requirement to have multiple servers with Socket.iO is that you have all your servers connected to a message queue. In this case, you can pick any one of the two that you have already running if you like, or set up a separate one dedicated to Socket.IO, maybe even make it RabbitMQ instead of Redis. Up to you. Then in your code, you have to configure the address of the message queue into your two `SocketIO` objects. Documentation: https://flask-socketio.readthedocs.io/en/latest/#using-multiple-workers.

**Comment by w-A-L-L-e** [comment]
Thanks for the help. So the mistake we made was using 2 redis servers instead of 1 (this was done for high robustness as our cto mentioned so when doing this the redis server is a single point of failure). So as a first step we can try using 1 redis server and then my above issues should be fixed. And then later on we can do a redis cluster http://redis.io/topics/cluster-tutorial if we want multiple redis nodes. Thanks for the quick replys Miguel it helped me a lot!

**Comment by rj919** [comment]
In the documentation it says: 
"Flask-SocketIO supports multiple workers behind a load balancer starting with release 2.0. "
If Nginx is used to balance the load between two or more servers on the same machine (but different ports), does each server need to be spawned as a separate process each with a single worker through something like "gunicorn --worker-class eventlet -w 1 module:app" or is there a server framework other than gunicorn which can spawn multiple workers and bind them to different ports?

**Comment by miguelgrinberg** [comment]
@rj919 Yes, the servers need to be spawn independently. You can use gunicorn or uwsgi if you like, or you can also run these servers directly (i.e. via `socketio.run()`, which for eventlet and gevent use a production ready web server).

**Comment by rj919** [comment]
Great. Thanks for the clarification. I will adjust my docker entrypoint accordingly.
