### ISSUE TITLE
Dynamic Namespace Creation

### ISSUE THREAD

**Issue by skortchmark9** [miguelgrinberg/Flask-SocketIO#344]
Hey Miguel,

I am doing some cool stuff with namespaces as a way to separate concerns for an application using socketio clients on the backend and frontend. I'm creating them on-the-fly from rest endpoints and then connecting a backend and frontend process to the same one. It creates the illusion of bidirectional communication: all events from web clients go to a single backend process, all events from the process go to all web clients, and the clients can join or leave the namespace as necessary.

The issue with dynamically creating the namespaces is that there isn't a great way to keep track of whether or not one has already been created. I have been using `socketio.server.manager.get_namespaces()`, but I sometimes find that after a server restart it has already been populated. (hypothesis: a client is reconnecting to the server before on_namespace is called and the namespaces path gets created somewhere?) As a result, I never call `socketio.on_namespace`, and then my custom namespace class behavior never kicks in.

So my questions are:

* is my hypothesis correct?
* do you have any suggestions about how to achieve the architecture I am aiming for?
* Is there a better way to keep track of the class-namespaces that have been registered by socketio.on_namespace?

**Comment by miguelgrinberg** [comment]
My understanding of the socket.io protocol is that namespaces are not meant to be dynamic, they are fixed and exist throughout the life of the application. What you are doing is really not a use case that was considered.

> is my hypothesis correct?

Yes. Clients have reconnect logic. If the server is restarted, the clients will right away try to connect, possibly before you get around to do your dynamic namespace configuration. And when the client passes a namespace name that hasn't been seen before, the server starts watching for events on it automatically, since it has no way to know it is a dynamic thing that doesn't have any handlers associated with it. As I said, the protocol was not created with the idea of dynamic namespaces.

> do you have any suggestions about how to achieve the architecture I am aiming for?

I think namespaces is not the right level you should be looking at. A namespace encapsulates the entire communication content of an application. In most cases one namespace is enough, though for complex pages that have two or more different sub-applications multiple namespaces may make sense.

My advice is that you check out the "rooms" feature to see if that works better for what you need to do. Clients can enter and leave rooms, that is functionality that is currently supported. It'll be a lot easier, I think. Alternatively, you can pass additional data in the event payloads to help you identify which communication channel you want.

> Is there a better way to keep track of the class-namespaces that have been registered by socketio.on_namespace?

Not sure I understand the question. A namespace is just a string value that is used to group event handlers. There is really no magic around them, the class based namespaces are no different, they just allow you to provide that grouping of event handlers in a way that is more convenient to you.

**Comment by skortchmark9** [comment]
Sweet, thanks for the speedy and detailed response.

Re: namespaces vs rooms

Yeah I was at one point trying to choose between namespaces and rooms, and maybe I didn't understand the protocol properly. I was hoping to use namespaces for a few reasons:
* Class-based namespaces are a really good mechanism for codifying all the events that can happen in a particular room. My application is getting to the point where its hard to keep track of the various inputs and outputs that can happen.
* Clients can dynamically connect / disconnect from namespaces without anything happening on the server (at least at the level of my application)
* Namespaces can have their own connect / disconnect handlers, so it makes it possible to use different authentication protocols for backend and frontend clients.

I guess there's no reason that this stuff couldn't be implemented on top of rooms, it just seemed like I got it for free with namespaces.

**Comment by miguelgrinberg** [comment]
I think you are not thinking about namespaces and rooms in the right way. Let me go over your statements one by one.

> Class-based namespaces are a really good mechanism for codifying all the events that can happen in a particular room.

Not really. Namespaces group related events, rooms group related clients. There isn't any connection between the two that I can see.

> My application is getting to the point where its hard to keep track of the various inputs and outputs that can happen.

If we are just talking about how these event handlers are organized in the code, then why don't you use Python modules or packages as a way to keep things manageable?

> Clients can dynamically connect / disconnect from namespaces without anything happening on the server (at least at the level of my application)

Clients can connect and disconnect as much as they want, that's technically true, but that's not really the intended use of Socket.IO. The protocol was created to support long lived connections with very low latency. Clients constantly connecting and disconnecting will cause overhead on both client and server sides, and obviously affect latency. If you want your clients to stay on a connection for a short amount time, then a REST API makes a lot more sense.

> Namespaces can have their own connect / disconnect handlers, so it makes it possible to use different authentication protocols for backend and frontend clients.

I'm not sure I understand this one. For static namespaces you can attach connect/disconnect handlers that use different authentication methods, since each namespace gets a dedicated handler, but how are you going to do that for namespaces that come and go all the time?

I think I still don't fully understand what problem you are trying to solve, but my recommendation is that:

- Use a single, hardcoded namespace.
- A client connection to the socket.io server is permanent, it ends when the user leaves the page.
- If a group of clients need to receive certain events, put those clients in a room, then emit the events to the room. Clients can join and leave rooms as they please, as this is a cheap operation.
- If a client needs to be kept out of all notifications for some time, remove it from your rooms, but keep it connected anyway.
- If you have a large number of event handlers, use standard Python modules and/or packages to keep your code organized. Do not use class-based namespaces, use function based handlers, because they are easier to break into multiple files.

Hope this helps.

**Comment by skortchmark9** [comment]
Okay, thanks for all the advice! I'll let you know how it goes.
