### ISSUE TITLE
Can we test target function in start_background_task?

### ISSUE THREAD

**Issue by geniousisme** [miguelgrinberg/Flask-SocketIO#373]
I wanna know how to test the function I execute in start_background_task, I didn't see you test this part in the test_socketio.py. Can you please give me some guidance abt this? Thx so much!

**Comment by miguelgrinberg** [comment]
There is really nothing to test, since the [implementation](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L555) of that function in this repository just calls the function of the same name in python-socketio, which in turns calls the one in python-engineio. There is a unit tests in this last package: https://github.com/miguelgrinberg/python-engineio/blob/master/tests/test_server.py#L737-L747.

**Comment by geniousisme** [comment]
Ok... but my question is more about how to get the response from the target function in start_background_task.  Here is my code: https://github.com/chaojiwan/ASE-ETLion-Team4/blob/master/ETLionServer.py#L32-L86. In this background function I also use socketio.emit from line 77 - 86. How can I get the result form it to test like get_received does?

**Comment by miguelgrinberg** [comment]
start_background_task is a non-blocking function. It will start the target function, but will not wait for it to finish, so it cannot return the return value of the target function.

If you need the main thread to have the result, you have to use a different mechanism by which the two threads can communicate. A simple option is to use global variables, like I did in the unit test I referenced you above.

**Comment by geniousisme** [comment]
Thx for such quick and informative response!
