### ISSUE TITLE
'Invalid session' using multiple uWSGI workers, gevent and redis

### ISSUE THREAD

**Issue by gesh** [miguelgrinberg/Flask-SocketIO#439]
Hello,

I have an issue regarding syncing uWSGI workers using redis. 
I am trying to start a few uWSGI workers but 'invalid session' messages are logged.

I've tried with RabbitMQ as well but without success. I saw that a few queues were created, so it seems flask-socketio connects to the RabbitMQ but I am not sure how many queues should be there (one per each worker or one for the all workers?). In the redis-cli new messages were appearing in parallel with the 'invalid session' logs. 

If I start the app with only one worker, everything is fine - no 'invalid session' messages appear.

[Here](https://gist.github.com/lovechguy/4829b41b10104c618f3a98cc121d3109) you can see my test application. 

The command I am using to start the app

`uwsgi --http :5000 --gevent 1000 --http-websockets --master --wsgi-file manage.py --callable app --processes 4
`

Do I miss something ? 

Please let me know if you need more details.

**Comment by dengxuesong** [comment]
i test this can only one process ， master,work,http

**Comment by miguelgrinberg** [comment]
As indicated in the documentation, if you use multiple workers, you must ensure sticky sessions are used. That is required because the Socket.IO protocol is stateful. I haven't ever looked into implementing the sticky sessions in uwsgi, what I've done is putting an nginx instance with the iphash load balancing algorithm in front of several single-worker uwsgi instances. I haven't checked, but it might be possible to do the same all in uwsgi.

**Comment by raynaya** [comment]
@lovechguy Did you find how to get this done in uwsgi ?

**Comment by lovechguy** [comment]
@raynaya No, I decided not to use flask-socketio and websockets at all.
