### ISSUE TITLE
Disabling reloader results in hang on KeyboardInterrupt

### ISSUE THREAD

**Issue by datspike** [miguelgrinberg/Flask-SocketIO#449]
If I'll run example with `socketio.run(app, use_reloader=False)` and close the script before any client connects to the server everything is fine, no exceptions is occuring
If I'll open the example page and than stop the script by Ctrl-C it hangs on `wsgi exiting`
Debugger shows that execution is waiting for rougtly 60 seconds and loops on 63 line of epolls.py (eventlet/hubs/epolls.py)
`def do_poll(self, seconds):
return self.poll.poll(seconds)`
Is this behaviour is ok?

**Comment by miguelgrinberg** [comment]
It's not an okay behavior, but it's also not a problem caused by this service. Not having a clean interrupt handler is a fairly common issue with web servers. I've seen the problem you mention in eventlet, and other somewhat similar problems in gevent, uwsgi, werkzeug, sanic, etc. See https://github.com/miguelgrinberg/Flask-SocketIO/issues/199.
