### ISSUE TITLE
events are blocking - even across multiple namespaces

### ISSUE THREAD

**Issue by hsvlz** [miguelgrinberg/Flask-SocketIO#460]
Hi,

when a single user calls an event that is **blocking** (with a sleep(100) for instance), all following messages even across different namespaces are blocked and queued.
However, if another user connects to the server while the first user is still blocked by the sleep, the second user is not blocked.

I have used your basic example, and run it directly from main. I have tried with different async modes, and even with gunicorn - this behavior is always the same.
Is that normal? (I would have thought that at least across different namespaces due to multiplexing, it would have not been blocking)

Thank you Miguel.

```
from flask import Flask, render_template, request
from flask_socketio import SocketIO, emit
from gevent import monkey
monkey.patch_all()

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode='gevent')

@app.route('/')
def index():
    return render_template('index.html')

@socketio.on('my_event', namespace='/test')
def test_message(*args):
    socketio.sleep(100)
    emit('my_response', 'response')

@socketio.on('my_ping', namespace='/test2')
def ping_pong(*args):
    print request.headers['Sec-Websocket-Key']
    emit('my_pong')

if __name__ == '__main__':
    socketio.run(app, debug=True)
```

**Comment by miguelgrinberg** [comment]
Yes, that's actually pretty normal behavior for asynchronous frameworks. All of them would have this problem (or feature, depending on how you look at it!)

My Socket.IO server will, by default, serialize events for a given client. That means that if you have an event handler that spends 100 seconds sleeping, any events that come while that happens will wait in a queue and be dispatched when the sleeping event returns. This is a default, you can allow concurrent events for a client if you pass `async_handlers=True` in your `SocketIO` constructor. But be aware that if you enable this option, it is up to you to prevent all those weird behaviors that can happen as a result of multiple handlers running concurrently. That means you may need to add locking and critical zones to prevent race conditions.

Another sort of similar option, without using the `async_handlers=True`, is to start background threads for the slow operations, so that your event handlers return quickly. Same disclaimer as above regarding locks and race conditions.

**Comment by hsvlz** [comment]
Thank you for answering so quickly Miguel!

I have tried with this async_handlers=True, and it works perfectly.

If using the default behavior, what is the potential buffer size, assuming a very long timeout and very long sleep? Also, is it fair to assume that the tcp ack is still performed, while the socket-io event ack is not done? (and therefore, the client will not resend again these messages...)

Can a similar behaviour to async_handlers=True be achieved with gunicorn?
