### ISSUE TITLE
socket.io scalability when clustering

### ISSUE THREAD

**Issue by hsvlz** [miguelgrinberg/Flask-SocketIO#480]
Hi Miguel,

I have read about the [scalability issues](https://medium.com/@3rdeden/cluster-fucks-when-scaling-socket-io-2c8ad1153332) in the design of socket-io when clustering because it seems that every node will subscribe to all rooms/handshake data/..., even for clients/rooms not currently used by such node.

Is that the case in your implementation of flask-socketio? What is the 'theoretical limit' in term of users assuming scaling to 100s of flask-socketio servers?

Thank you

**Comment by miguelgrinberg** [comment]
That article is very old, it applies to the 0.x JavaScript server versions. I'm not sure those problem apply to the 1.x and 1.x JS servers, actually.

In any case the design of python-socketio (the main dependency in Flask-SocketIO) is not like that. You have multiple processes, all connected to a pub/sub channel in your Rabbit/Redis/etc message queue. This is a single subscription per node.

When an event is emitted through a node, that node posts the emit to the queue, and all subscribed nodes will get it and run it on the clients they know about. That's basically it.

**Comment by hsvlz** [comment]
I can see why it could become an issue on the long run with too many nodes. If each node needs to process all updates coming from other nodes, even though this update may be irrelevant to this node because no user of this node is affected by it, then this may lead to a bottleneck.

Have you potentially considered implementing something more stateful, notably when you have Redis as both queue/db? For instance every connected user would be matched to a node, and before dispatching a message between nodes, redis would look up to which node it should dispatch it? This could even be done with a lua script (locate user + dispatch to the correct queue).

**Comment by miguelgrinberg** [comment]
@hsvlz I'm not sure how that would be implemented, it does not seem possible with the way things are structured currently.

There are basically three kinds of emits that need to be handled:

1. Addressing all the clients
2. Addressing all the clients that joined a given room
3. Addressing a single client

Obviously for case 1 you need all nodes to participate, I don't see how to avoid this. This type of emit is obviously expensive, if you have 1 million clients, that means you need to write to as many sockets to carry out the broadcast.

For case 2, the node in which the emit originates has no way to know where are all the other clients that are in the room in question. Clients are assigned to different nodes supposedly by a load balancer, so they are going to be randomly distributed across the nodes regardless of their room participation. A given node does not have the complete client list and does not have the complete room list, it only knows about the clients it is connected to, and the rooms those clients have joined. In the current implementation, the originating node posts on the pub/sub queue so that each of the other nodes can run the same emit against its own client list. If a node has no clients in the target room, then it will quickly dismiss the event, because the query that gets the list of clients in that room will come up as an empty list.

Case 3 is currently handled exactly as case 2. The id that is assigned to each user, can also be used as a room name when targeting that user. So all the nodes will get the emit to this client, and only one of the nodes will actually know about that room/client id.

I did not consider using a consolidated database of all clients, as you suggest. While it does have the advantage that it would make nodes stateless, I think performance will suffer, since now the database becomes a bottleneck for these hundreds of nodes that cannot work on their own. And there is also the concern about reliability. Using a standalone redis instance would be a huge mistake, since that is a single point of failure. In the current architecture, if a node dies, then all the clients connected to that node are dropped, and then they immediately join back, now going to one of the healthy nodes. If your redis goes down, then your application is down. You would need to implement a clustering solution, which affects performance even more.

**Comment by hsvlz** [comment]
@miguelgrinberg I agree, this would shift the burden to the db. 

Apart from case 1, the db would have to know about each room and each participant, along with their server. If executed redis side in lua, what used to be a simple put will become a combination of a few get and a put. Though I have not benchmarked this implementation, this seems like a marginal additional cost.

Regarding the clustering, you would need it anyways. Because if redis dies, then your nodes would not communicate anymore and the service would be partially down. A likely implementation is to have multiple slaves ready to be promoted in such event, and because they are asynchronously updated, the cost is again marginal. But potentially their state would be inconsistent for a short period of time.

Without a more stateful interconnection between the nodes, I fear that if each node has to process every single event coming from each user, no matter how quickly it will be discarded, will surely keep the nodes so busy that they will eventually become irresponsive. However this is uncharted territory as I have not tested it.

**Comment by miguelgrinberg** [comment]
> Regarding the clustering, you would need it anyways.

Yes, agreed, and in particullar with RabbitMQ it is fairly easy to stand up a cluster with mirroring and replication. But using a single queue process as pub/sub without any storage makes it less of a problem if that process crashes and needs to be restarted. For a short amount of time the nodes will not talk to each other, but as soon as the new message queue is up you are back to normal. In fact, because the message queue is (sort of) stateless, you could just set up a poor man's clustering just by having two processes, the master and the backup behind a load balancer that is configured to forward 100% of the traffic to the master. When a health check for the master fails, the load balancer is reconfigured to promote the backup to master and starts sending all the traffic there, while in the background another backup process is started. The recovery would not be as easy when you have all the client sessions in the middle.

> Without a more stateful interconnection between the nodes, I fear that if each node has to process every single event coming from each user...

I don't have a measure of this cost for an installation with hundreds of nodes. For a handful of nodes this has not been a problem in my experience, because in most cases, events need to reach clients hosted by all nodes anyway.

**Comment by hsvlz** [comment]
> because in most cases, events need to reach clients hosted by all nodes anyway.

Agreed - my use case is actually 100% 1-to-1 communication, hence that's why it would benefit the most of a smarter routing.

From your experience, what is the best queue? Redis, RMQ, ...? You did mention clustering of RMQ but truth is, you also have to be ready to deal with network partition in mnesia when using cloud services.

Assuming you would like to remove any business logic from a webserver and dispatch every event to queues, and operate some routing, have you ever given some thoughts about what is the best way to achieve this, notably when it comes to durability (not losing events), order, flexibility of routing?

**Comment by miguelgrinberg** [comment]
> From your experience, what is the best queue? Redis, RMQ, ...?

I tend to prefer Redis for development due to easy of install/setup. But I have seen more production deployments with RMQ than Redis.

> have you ever given some thoughts about what is the best way to achieve this, notably when it comes to durability (not losing events), order, flexibility of routing?

If the purpose is to support 1-to-1 communication only, I would look into using a predictable load balancing algorithm, so that given some characteristic of your target client (IP address, etc), you can algorithmically determine which node owns that client. Then you may not even need a queue at all, the communication can be node to node (though work queues for each node would certainly be useful in extreme load situations as a buffer).

**Comment by hsvlz** [comment]
>  work queues for each node would certainly be useful in extreme load situations as a buffer

Indeed, this is a good benefit - probably instead of using a shared queue, the node forwarding the event would dispatch to a specific queue only for that node.

What do you recommend if you want to add a microservices capability to the nodes, i.e have aynchronous rpcs, etc?

**Comment by miguelgrinberg** [comment]
Not sure you need anything else. Requests from other microservices can go in these queues as well. I can't really recommend an RPC mechanism that I like. I find that RPC promotes coupled designs, where one service invokes specific functions in another, and needs to know arguments, etc. I prefer a loose association between services. When a service needs another service to do something, it makes a request (HTTP, message queue, direct socket connection, doesn't matter how) saying what it wants done, not what function to invoke. It is a subtle difference, but important to have evolvable microservices, in my experience.

**Comment by hsvlz** [comment]
>  I prefer a loose association between services.

I agree. Which framework would you recommend, preferably queue-based so it allows durability? 

Also, would you see a benefit in moving the business logic entirely out of the webserver and put it in a service?

**Comment by miguelgrinberg** [comment]
In my opinion this is simple enough that it does not require a framework, other than the code that allows you to write or read from the queue. I have implemented this with Redis and with Kombu (mainly for RMQ). Feel free to look at the code in project python-socketio for ideas.
