### ISSUE TITLE
possible to use https in socketIO server?

### ISSUE THREAD

**Issue by wiwengweng** [miguelgrinberg/Flask-SocketIO#490]
Hi, Miguel. I am using SocketIO as socket server and also http server. 

````
socketio = SocketIO(app, async_mode=async_mode, message_queue='redis://')
# WSGIServer(('0.0.0.0', 80), app).serve_forever()
socketio.run(app, host='0.0.0.0')
````

Is it possible to use https only for http server, but not effect socket server?:D Maybe my expression is poor, and I hope you can understand.

**Comment by chisaipete** [comment]
I think I'm actually seeing the same issue, but restated a different way:

I'm unsure of how to start my flask server which requires https for security through the socketio.run() wrapper.  The ssl_context and other https parameters seem to go largely ignored and socketio seems to default to http protocol.

**Comment by miguelgrinberg** [comment]
@wiwengweng the web server is a single one, so you cannot have http on one and https on the other part. What you can do is run two separate servers, and then add nginx as a reverse proxy. The nginx configuration can specify that you want to listen on ports 80 and 443.

@chipsenkbeil your question seems to be more about how to set up SSL, which depends on the async framework you are using. The `ssl_context` option works for the Flask development web server, but will not work for eventlet or gevent, because each have their own SSL support. So you need to look at the docs for the web server that you are using to see how to enable SSL.

**Comment by chisaipete** [comment]
Ah! Thanks for the correction and hint!

**Comment by wiwengweng** [comment]
Thanks, Miguel. Would try then. :D

**Comment by dhhagan** [comment]
@chisaipete Any chance you're willing to share what worked for you with SSL/Gunicorn/Eventlet?

**Comment by miguelgrinberg** [comment]
@dhhagan not sure if this is an option you are open to explore, but I always set up SSL to be terminated at nginx. The communication between nginx and the application does not use encryption. This is how I host my blog, for example. An example nginx config for this set up is in my Flack project: https://github.com/miguelgrinberg/flack/blob/master/webserver/nginx/flack.conf.

**Comment by dhhagan** [comment]
Hey @miguelgrinberg . That's exactly what I'm trying to do (and was using your example), but have run in to trouble with debugging nginx that is driving me nuts, so I was looking for other examples..I'll keep hacking away at it since it seems like the best way forward. If doing that, do I still need to directly send the cert files?

**Comment by miguelgrinberg** [comment]
> If doing that, do I still need to directly send the cert files?

Explain this. I don't understand what you mean.

**Comment by dhhagan** [comment]
Nevermind. I was mixing up the socketio.run() server with gunicorn (which I am using). I suppose if I were using the former, I would need to tell it where the ssl certs were..? I have nginx taking care of all that as of now.

**Comment by miguelgrinberg** [comment]
Yes, each framework and/or web server does this in a different way. For gunicorn, you pass the info in cli arguments. If you use eventlet or gevent via `socketio.run()`, then each has its own specific arguments to pass the cert and the private key files, which you need to pass in the `run()` call.

**Comment by chisaipete** [comment]
@dhhagan Yes! Sorry.  I had to use some development versions of eventlet and gunicorn in order to get it all working in my development environment (Ubuntu on Windows 10).  I believe all the changes I made were:

`pip install -U https://github.com/eventlet/eventlet/archive/master.zip`
`pip install -U https://github.com/benoitc/gunicorn/archive/master.zip`

Remember to monkeypatch eventlet:
`import eventlet`
`eventlet.monkey_patch()`

And then to run:
`gunicorn --worker-class eventlet -w 1 --certfile cert.pem --keyfile key.pem -b 0.0.0.0:5500 app:app`

**Comment by hduoc2003** [comment]
Hi @miguelgrinberg, now I am using a Nginx with TSL managed by certbot in my host, and one Nginx mapped to 88 in my docker container (does not have TSL). In this container, I use gunicorn for my Flask app, and use socketio too. And now my socket can not communicate with my site, I wonder how it can be resolved without adding --certfile and --keyfile in my gunicorn run command because I just want to keep them as unrelated as possible. Sorry if it's a stupid idea (and for my poor English). Tks!!

**Comment by miguelgrinberg** [comment]
@hduoc2003 If the proxy URL that you put in your Nginx configuration is http:// instead of https://, then nginx will not use encryption when it talks to your container, it will only use encryption when talking to the client.

**Comment by hduoc2003** [comment]
@miguelgrinberg I am doing that way and can not use websocket :((

**Comment by saad-ashfaq** [comment]
> @dhhagan not sure if this is an option you are open to explore, but I always set up SSL to be terminated at nginx. The communication between nginx and the application does not use encryption. This is how I host my blog, for example. An example nginx config for this set up is in my Flack project: https://github.com/miguelgrinberg/flack/blob/master/webserver/nginx/flack.conf.

@miguelgrinberg I have set up Nginx as reverse proxy for my Flask-SocketIO based web servers similar to your config above. So SSL is configured at Nginx with HTTP to HTTPS redirection whereas the communication between Nginx and the web servers happens over HTTP. However, if I use Flask's `url_for` with `_external=True` inside a SocketIO event handler to get the absolute URL including the scheme and the hostname, it always returns `http` rather than `https` as the scheme. Using `url_for` with `_external=True` in regular requests outside SocketIO event handlers returns `https` as expected. Is this expected behaviour and any idea on how to resolve this? 

It should be noted that I am using [ProxyFix](https://flask.palletsprojects.com/en/3.0.x/deploying/proxy_fix/) to tell Flask that it is behind a Proxy.

**Comment by miguelgrinberg** [comment]
@saad-ashfaq the ProxyFix middleware is for the Flask application, it does not run for Socket.IO events, so yes, this is expected.

**Comment by miguelgrinberg** [comment]
> Just to clarify, are there any security implications due to the communication between Nginx and the SocketIO server not being encrypted even though the client and Nginx channel is encrypted?

It really depends. If Nginx and your application are on the same machine then the risk is small, as your server would need to be compromised for this traffic to leak.

**Comment by saad-ashfaq** [comment]
Makes sense. Thanks for your response.
