### ISSUE TITLE
Facelift

### ISSUE THREAD

**Issue by igorbpf** [miguelgrinberg/Flask-SocketIO#513]
I'm newbie to socketio and flask-socketio, but I wonder if there is any way to make the app look like whatsapp/telegram and give different alignments and colors to messages sent by yourself and messages sent by other users. Thank you!

**Comment by miguelgrinberg** [comment]
Yes, but that is not the focus of this package. You would use HTML/CSS/JS to do the styling of your application, or maybe use a styling framework such as Bootstrap.

**Comment by igorbpf** [comment]
Yeah!  I understand that, @miguelgrinberg! The facelift will be done with bootstrap or sort of thing. My doubt is concerned to how can I differentiate the author of the message? There is probably an easy solution, but I'm a newbie! sorry!

**Comment by miguelgrinberg** [comment]
Well, the messages that your client-side app is going to receive are all going to come from the server, the Socket.IO protocol doesn't really have a concept of a sender, because it is always a client-to-server or server-to-client. Your application needs to add information of the message author in the payload that is being sent by the server, along with any additional information that the client-side app will use to determine the styling of each message.

**Comment by igorbpf** [comment]
I see! That's what I want! I'll read the docs and try to implement it! Thank you, @miguelgrinberg!
