### ISSUE TITLE
Android disconnecting when: async_mode='gevent'

### ISSUE THREAD

**Issue by badjano** [miguelgrinberg/Flask-SocketIO#528]
Log:
03159cf3d98f4a7985e84f8eb5c11be0: Received packet PING data None
03159cf3d98f4a7985e84f8eb5c11be0: Sending packet PONG data None
c956f97f2309441e9a5a5f0cffb1ad3f: Received packet CLOSE data None

I am not sending this packet CLOSE from Android, and I investigated and there was only an error emitted from Android between that PONG and CLOSE with this exception:
io.socket.engineio.client.EngineIOException: xhr poll error

This only happens on gevent, eventlet works fine, no reconnection after PING, PONG.

I needed to use gevent for emitting messages in other threads.

**Comment by miguelgrinberg** [comment]
Not sure if you noticed that the CLOSE packet is a different connection from the PING/PONG. You are mixing logs from different clients here.

> I needed to use gevent for emitting messages in other threads.

Eventlet and gevent are fairly similar. Nothing prevents you from using eventlet to emit from background threads. Can't really imagine what can cause gevent to break and eventlet to work, but if nothing helps, I'd say stick to eventlet.

**Comment by badjano** [comment]
Yeah, I can't figure out either, but on gevent Android keeps reconnecting and on eventlet it stays connected. And I tried everything to make emit work on another thread ( using threading.Thread ) but it only worked with gevent

**Comment by miguelgrinberg** [comment]
You can't use `threading.Thread` with gevent/eventlet frameworks. You have three options:

- Use the `socket.start_background_task()` function to start your thread. This function uses the proper method for each framework.
- Monkey patch the standard library through eventlet or gevent monkey patching functions. This changes `threading.Thread` so that it is compatible with your framework.
- Use your chosen framework's own options to start background threads.

**Comment by badjano** [comment]
I did not know about start_background_task, it worked perfectly, thanks!
