### ISSUE TITLE
Distributed rooms

### ISSUE THREAD

**Issue by xarg** [miguelgrinberg/Flask-SocketIO#551]
Imagine a simple chat app where you can join a chat room and you want to see who is already in the same chat room as you. Let's call this feature the 'chat lookup'.

Currently when a client joins a room their `sid` is stored locally in a dict on the server object. One way to implement the 'chat lookup' is to lookup all the `sids` in your room from the local dict. However when there are 2 or more socketio servers behind a load balancer this is problematic since the `sids` are split between servers. Example:

```
server1:
room-1: [sid1, sid2, etc..]

server2:
room-1: [sid3, sid4, etc..]
```

Since messages can already be passed using `ampq` for example, why are the rooms not synced between flask-socketio servers as well? Is this because the intention of rooms are single instance only? Not implemented yet or some other reason?

What I'm think of doing to solve this is having a session affinity for the load balancer based on the room name thus putting everyone in a room on the same server. Intuitively this should work, but I'm afraid that it will lead to overloading a single instance (a few big customers on the same server).  

If the rooms are distributed between servers (like in the example above) then it will lead to more traffic between the instances and their queues + the extra complexity (aka many many bugs) of managing the syncing of rooms.

@miguelgrinberg would be super grateful to know your take on this.

**Comment by miguelgrinberg** [comment]
Any data that cannot be obtained through functions officially documented is not guaranteed to be there in future releases. I reserve the right to change these at any time.

The decision to not provide lists of clients in a room is intentional. As you clearly understand, the query to obtain that list can be expensive, as all servers need to be queried for their internal lists, and then the lists need to be merged into one. For large number of clients this can put a lot of traffic in the queue, something that with the current design is avoided. I don't want to say that I would never allow such a feature, but I'll just say that it isn't high in my priority list due to the potential performance implications.

My reasoning is that your application must have a database, and it would be fairly easy for you to record the room(s) there, in a way that is more efficient.

**Comment by xarg** [comment]
Thanks for the fast reply @miguelgrinberg! I will probably go the DB way. I'll close this issue.
