### ISSUE TITLE
unit test when failed authentication on 'connect'

### ISSUE THREAD

**Issue by hsvlz** [miguelgrinberg/Flask-SocketIO#571]
Hi Miguel,

Let's assume this handler:

```
    @socketio.on('connect')
    def on_connect():
      return False #this would be returned if failed authentication

```
Normally the browser received  401 when return False.

What is the best way to unit test this ? (without having to rely on a lack of emit that could have been sent if authentication was successful)

And same question when connecting to a namespace this time?

Thanks!

**Comment by miguelgrinberg** [comment]
@hsvlz When you return `False` from the connect handler there is no 401, the server simply removes the client from the connected list, and then sends a close request, which makes the client close. If you get a rogue client that ignores the close and starts sendng data, since this client isn't a known client, any data that comes from it will be discarded.

For a unit test, I would just call the function directly and check the return value. If you want to write an end-to-end test that does everything for real, there are many ways to do it. For example, you can set a global variable when the code path that returns `False` is reached, or something more sophisticated like signalling an event.

**Comment by TheJKFever** [comment]
I have a similar issue. I want to return something to the user on a failed authentication such as a 401, or some sort of error message, but I don't want to open a socket connection because I don't want to allow for anyone to open unauthenticated socket connections. Is there any way on the client to tell that the request was rejected in this way? If I try to emit some message, it doesn't work if I return False or disconnect right afterwards. Any suggestion?

**Comment by miguelgrinberg** [comment]
@TheJKFever if you return `False` the client will receive a `CLOSE` packet, which means that the connection was rejected.
