### ISSUE TITLE
Why pass app again in run() when it's already passed in the constructor?

### ISSUE THREAD

**Issue by Knifa** [miguelgrinberg/Flask-SocketIO#577]
Straight from the first example.

```from flask import Flask, render_template
from flask_socketio import SocketIO

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

if __name__ == '__main__':
    socketio.run(app)
```

`SocketIO` already knows what `app` is because it's passed in the constructor. Why pass it again when calling `run()`? Makes it a little cumbersome when starting the dev server from code with an app factory because now you need to pass around two objects.

**Comment by miguelgrinberg** [comment]
Flask extensions are not supposed to store the application instance in its own state, they actually have to store their state in the application, so that you can use the same Flask extension instance with multiple applications. I agree that it seems weird to have to pass the app twice, but that way the extension behaves in the expected way.

**Comment by Knifa** [comment]
Thanks for the explanation.
