### ISSUE TITLE
Flask-socketio not working with Flask-Login

### ISSUE THREAD

**Issue by deounix** [miguelgrinberg/Flask-SocketIO#593]
I can't use Flask-Login inside Flask-socketio events

![pic-20171127-012433](https://user-images.githubusercontent.com/17798647/33245569-50840c0a-d312-11e7-9bc3-0906a49cdbd3.png)

I'm using request as http client and socketIO-client-2 as socket.io client.

**Comment by miguelgrinberg** [comment]
My guess is that the Socket.IO python client does not send the session cookie, where Flask-Login records the authenticated user. I assume you are sending the cookie on your HTTP request, correct? The same thing needs to be done for Socket.IO, so you'll need to check if and how this client can send cookies.

**Comment by deounix** [comment]
thank u.
another question: for a realtime chat server

it's a bad idea to check if user is authenticated or not using flask-login with mysql in every events

in auth dec there is a : if current_user.is_authenticated

@socketio.on('msg')
@auth

like if I'm trying to get user phone and check for auth and and ....etc before the event done

what should I do in this case? can I let flask login to store user data in memory ?

**Comment by miguelgrinberg** [comment]
You don't have to check credentials in every event, checking in the connect handler is enough. Socket.IO events are not the same as HTTP requests, the Socket.IO protocol itself creates a session when the connection is established, so there is no way for a non-authenticated client to "hack" its way without passing through the connect handler.

**Comment by tommypacker** [comment]
Ran into the same issue... any idea on how to send the session cookie from the client? Thanks again for writing this awesome library

**Comment by miguelgrinberg** [comment]
As I said above, the connection event will send the session cookie, so your connect handler has access to `current_user` from Flask-Login. In subsequent events you can also use `current_user` if you like, but checking credentials isn't necessary.

**Comment by tommypacker** [comment]
Hmm so for some reason I keep running into the issue where the session I'm checking for in my socket events doesn't contain the user-id needed for flask-login (therefore my current_user isn't valid). I thought it was because my client wasn't sending in the session cookie, not sure if you have any other ideas.

**Comment by miguelgrinberg** [comment]
Are you hosting your SocketIO server on the same URL as your HTTP stuff? If yes, then the cookie should be going in the connect request. This should be easy to check in the network tab of your browser's debugger.

**Comment by tommypacker** [comment]
Ah, I messed up a line in my client code. Thanks a bunch!

**Comment by DrOncogene** [comment]
Hi @miguelgrinberg the current_user global is returning an anonymous user from within the connect handler after login with login_user() from flask-login. Seems to be a session cookie issue. My client is on the frontend/browser using socket.io js client. How do I grab and send the session cookie generated by flask-login in order to send it for the connect handler?


> My guess is that the Socket.IO python client does not send the session cookie, where Flask-Login records the authenticated user. I assume you are sending the cookie on your HTTP request, correct? The same thing needs to be done for Socket.IO, so you'll need to check if and how this client can send cookies.

**Comment by miguelgrinberg** [comment]
> How do I grab and send the session cookie generated by flask-login in order to send it for the connect handler?

If the cookie is set, the browser should send it automatically, you shouldn't need to do anything.

**Comment by DrOncogene** [comment]
> > How do I grab and send the session cookie generated by flask-login in order to send it for the connect handler?
> 
> If the cookie is set, the browser should send it automatically, you shouldn't need to do anything.

Then why is current_user returning an anonymous user inside the connect handler and other event handlers after calling `login_user()` in the login route after authentication?

**Comment by miguelgrinberg** [comment]
@DrOncogene Have you confirmed that the browser is sending the session cookie in the Socket.IO connection request? The most logical explanation is that the browser isn't sending the cookie, so in that case looking for a solution in the Flask-SocketIO side makes no sense, since the problem would in how your application logs users in.
