### ISSUE TITLE
Appending to session variable overwrites 2nd value

### ISSUE THREAD

**Issue by KietnaQuTak** [miguelgrinberg/Flask-SocketIO#594]
Hello Miguel. Currently I'm writing a chat with Flask-SocketIO and thanks to Your article https://blog.miguelgrinberg.com/post/flask-socketio-and-the-user-session I finally realized what is the cause of session different behaviour, but there is still one thing I don't understand.

Normally in Flask when I declare a session as an array `session['example'] = [value]` and later append to this variable data is added to the end of provided session variable. Somehow same thing inside Flask-SocketIO creates session variable as an array, adds first and second value but later second value is replaced by newly appended values instead adding them to the end of array. Currently I have set `manage_session=False` and `SESSION_TYPE = 'filesystem'`. Am I missing something or is it working as intended?

For example bellow code after several page refresh and reconnects to chat always returns 3 lines ("session[example] exist" and two different times, where the first one is always the same and second one is changing on every reconnect).

```
@socket_io.on('connect', namespace='/chat/')
def event_connect():
    if session.get('examples', None):
        print('session[examples] exist')
        session['examples'].append(str(datetime.now().time()))
    else:
        print('creating session[examples]')
        session['examples'] = [str(datetime.now().time())]

    for example in session['examples']:
        print(str(example))
```

**Comment by miguelgrinberg** [comment]
I suspect this is because your way of changing the session goes undetected. Flask sessions have a `session.modified` attribute that is `True` when a change is made. Appending to an existing list does not make `modified=True`, so your change is dropped. Try adding `session.modified = True` to your handler to see if that fixes the problem.

My thinking in honoring the `modified` attribute is that if not, every event is going to waste time saving the session. For a HTTP request this isn't a huge deal, but with Socket.IO events it could affect performance if you have a lot of traffic.

**Comment by KietnaQuTak** [comment]
Thank You Miguel, adding `session.modified = True` solves the problem :-)

Thanks for advice I will definitely change the way of storing data to something else than sessions. I was trying to detect when user was disconnected from chat or refreshes page and rejoined same conversations. That's why I was trying to store chat timestamps in sessions, then on 'connect' event I was checking if this session variable exist and if chat room is still opened.
