### ISSUE TITLE
eventlet won't run threads with debug=True

### ISSUE THREAD

**Issue by jwkvam** [miguelgrinberg/Flask-SocketIO#617]
My use case is I want to have some functions run on a timer, which I accomplish with `eventlet.sleep`.

Here's an example
```
from flask import Flask
from flask_socketio import SocketIO
import eventlet

app = Flask(__name__)
app.debug = True
socketio = SocketIO(app)

@app.route('/')
def index():
    return 'hello'

def foobar():
    print('foobar')
    eventlet.sleep(5)
    eventlet.spawn(foobar)

if __name__ == '__main__':
    print('main')
    eventlet.spawn(foobar)
    socketio.run(app, host='0.0.0.0', port=9991)
```
If I have `debug=True` then I don't see any `foobar` prints. If I set `debug=False` then I see foobar print out every 5 seconds as expected.

Versions:
Flask: 0.12.2
Flask-SocketIO: 2.9.3
Eventlet: 0.22.0

**Comment by miguelgrinberg** [comment]
This is because of the reloader, which only runs in debug mode. Your background scheduled job will run on the parent process, which is the reloader. It appears that the reloader does not play nice with eventlet and does not allow other tasks to run. The child process, which runs the web server, never sees the first spawn, so the background task never starts in the child.

You can run in debug mode, but with the reloader, and then your tasks run fine:

    socketio.run(app, host='0.0.0.0', port=9991, use_reloader=False)

**Comment by jwkvam** [comment]
Thanks! I see now that this is basically a duplicate of #567 and have also followed some advice there. I will close this.
