### ISSUE TITLE
reload credentials on disconnection

### ISSUE THREAD

**Issue by plockaby** [miguelgrinberg/Flask-SocketIO#628]
This is a feature request. Right now connections with kombu are made by passing in a connection string, like this:

```
socketio.init_app(app, message_queue="amqps://username:password@example.com:5671/vhost", channel="monitor", path="/stream")
```

In my use case, the username and password are read from a file. If the password for the user changes then the file is updated with the new password. If the connection is maintained then the password changing makes no difference. But if the connection goes away (e.g. a failover or a restart of the amqp server) then flask-socketio will sit there and try to connect with the invalid password and there is no way for me to tell it to use a new password without restarting the application. So my feature request is for a way to pass flask-socketio a function that will return a connection string so that I can give it a new password on a reconnect to the message bus.

**Comment by miguelgrinberg** [comment]
There is a way you can implement this now.

Instead of passing a `message_queue` argument, you can pass a `client_manager` instance. In your case this is going to be a `socketio.KombuManager` instance, provided by the package `python-socketio`. When you pass a URL, Flask-SocketIO creates the instance itself ([here](https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/flask_socketio/__init__.py#L172-L180) is the logic that does this).

You can create a subclass of `KombuManager` that uses your own connection logic. For example, you can override the [_connection()](https://github.com/miguelgrinberg/python-socketio/blob/master/socketio/kombu_manager.py#L65) method to build the URL dynamically.

**Comment by plockaby** [comment]
That works for me. Thank you for the information!
