### ISSUE TITLE
greenlet.error: cannot switch to a different thread

### ISSUE THREAD

**Issue by Vayel** [miguelgrinberg/Flask-SocketIO#65]
Hi!

I installed Flask-SocketIO on my Fedora and the following error displays : 

``` bash
[vincent@localhost controller]$ python server.py 
 * Running on http://0.0.0.0:5000/
 * Restarting with reloader
Unhandled exception in thread started by <function run_server at 0x8ee456c>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask_socketio/__init__.py", line 242, in run_server
    self.server.serve_forever()
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 284, in serve_forever
    self._stop_event.wait()
  File "/usr/lib/python2.7/site-packages/gevent/event.py", line 77, in wait
    result = self.hub.switch()
  File "/usr/lib/python2.7/site-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
greenlet.error: cannot switch to a different thread
```

*_server.py : *_

``` python
# -*-coding: utf-8 -*-
from flask import Flask
from flask.ext.socketio import SocketIO, emit

from controller import Controller
from map import Map
from doser import Doser
from locator import Locator

app = Flask(__name__)
app.debug = True
socket = SocketIO(app)

@socket.on("load-map")
def load_map(data):
    map_ = Map(data)

    # Notify modules
    if map_.is_valid():
        emit("map", map_.data) # Client
    else:
        emit("map", {}) # Client

@app.route("/")
def home():
    with open("templates/home.html", "r") as f:
        return f.read()

if __name__ == "__main__":
    # app.run(host="0.0.0.0")
    socket.run(app, host="0.0.0.0")
```

I get the same message on Raspbian.

Is it due to Flask-SocketIO ?

Thanks!

**Edit :** with debug mode disabled, it seems to work :

``` bash
[vincent@localhost controller]$ python server.py 
127.0.0.1 - - [2014-10-26 13:05:42] "GET / HTTP/1.1" 200 1142 0.014441
^CKeyboardInterrupt
Traceback (most recent call last):
  File "server.py", line 31, in <module>
    socket.run(app, host="0.0.0.0")
  File "/usr/lib/python2.7/site-packages/flask_socketio/__init__.py", line 247, in run
    self.server.serve_forever()
  File "/usr/lib/python2.7/site-packages/gevent/baseserver.py", line 284, in serve_forever
    self._stop_event.wait()
  File "/usr/lib/python2.7/site-packages/gevent/event.py", line 77, in wait
    result = self.hub.switch()
  File "/usr/lib/python2.7/site-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
KeyboardInterrupt
[vincent@localhost controller]$
```

**Comment by piejanssens** [comment]
@miguelgrinberg This also appears to be needed in combination with flask-apscheduler: https://github.com/miguelgrinberg/Flask-SocketIO/issues/65

**Comment by advance512** [comment]
If you see this in the context of debugging using PyCharm, try this:

Go to Settings --> Build, Execution, Deployment -> Python Debugger.
In that dialog, you'll see a "Gevent compatible" checkbox. Not sure how it got unticked in the new project.

Tick that option and enjoy!

**Comment by akapit** [comment]
Could be that also happens when using blueprints?

**Comment by miguelgrinberg** [comment]
@akapit using Flask blueprints should not have any effect on gevent, but what you do in those blueprints might.

**Comment by gitavi** [comment]
Is there any solution to this in the context of debugging using vscode?

**Comment by miguelgrinberg** [comment]
There is a `gevent` configuration option for vscode that needs to be `True`. See https://code.visualstudio.com/docs/python/debugging#_gevent.

**Comment by cedricdv** [comment]
> If you see this in the context of debugging using PyCharm, try this:
> 
> Go to Settings --> Build, Execution, Deployment -> Python Debugger.
> In that dialog, you'll see a "Gevent compatible" checkbox. Not sure how it got unticked in the new project.
> 
> Tick that option and enjoy!

This!

**Comment by gerazenobi** [comment]
Hi @miguelgrinberg, although we are not using `Flask-SocketIO` we have seen this issue within our Flask APIs (that end up using a library that imports `grequests`); since you might know more about this subject I though I'd test my luck and ask you: 

would you have any idea why we seem to see this issue only when running an API locally ?  e.g.:
```python
#api.py
if __name__ == "__main__":
    app.run(host="127.0.0.1", port=9999, debug=False)
```
but not seen when the API is run through `uwsgi` in a production environment ?
```python
#run.py
from ....api import app # called by uwsgi
```

Thanks in advance for any insights :)

**Comment by miguelgrinberg** [comment]
My understanding is that this error comes up when you are mixing gevent greenlets with real threads. If you were to make sure you use greenlets for everything then you should be fine. If you do need to have some real threads in there, then you should use greenlets in a single thread to avoid this problem.

**Comment by gerazenobi** [comment]
I see. Our `uwsgi` is not configured in `gevent` mode hence why I would't have though it should fail in some sort when _half patched_ by the library `grequests` (`curious_george.patch_all(thread=False, select=False)`

If I gather more info on this I will happily share it 👍 

Thanks for your response!

**Comment by miguelgrinberg** [comment]
The problem is that greenlets are bound to the thread in which they were created. What you are doing with grequests is likely causing greenlets to be accessed from different threads.

**Comment by gerazenobi** [comment]
well the problem is that it seems to work fine but I was expecting the opposite given the behaviour when executing locally hence my confusion on the subject 😅

**Comment by PravinRanjan10** [comment]
> I would like to add that I monkey patch only in the `__main__` guard and that works as well.
> 
> ```
> if __name__ == '__main__':
>     from gevent import monkey
>     monkey.patch_all()
> ```
> 
> For me, this is important so that Celery, which imports some of my scripts, wouldn't hang, see #61.
> 
> Finally, if you're using PyCharm/PyDev, enabling File->Settings..->Python Debugger->Gevent compatible debugging might be required.

Thanks. It resolved my issues.

**Comment by sylnsr** [comment]
Regarding "Gevent compatible" setting .. it wont work in every situation. As of now, there is confirmed issue ("reproduced" status) that JetBrains confirmed. See https://youtrack.jetbrains.com/issue/PY-43676

**Comment by netwang** [comment]
here is the requirements.txt. Could you help me to check which package  is not compatible with eventlet? Thanks!

atomicwrites==1.4.0
attrs==21.4.0
bidict==0.22.0
click==8.1.3
colorama==0.4.5
cx-Oracle==8.3.0
dnspython==2.2.1
eventlet==0.33.1
Flask==2.1.2
Flask-Cors==3.0.10
Flask-SocketIO==5.2.0
greenlet==1.1.2
importlib-metadata==4.12.0
iniconfig==1.1.1
itsdangerous==2.1.2
Jinja2==3.1.2
ldap3==2.9.1
MarkupSafe==2.1.1
numpy==1.23.0
packaging==21.3
pandas==1.4.3
pip==22.0.4
pluggy==1.0.0
py==1.11.0
pyasn1==0.4.8
PyJWT==2.4.0
pyparsing==3.0.9
pytest==7.1.2
python-dateutil==2.8.2
python-engineio==4.3.2
python-socketio==5.6.0
pytz==2022.1
setuptools==58.1.0
six==1.16.0
tabulate==0.8.10
tomli==2.0.1
Werkzeug==2.1.2
zipp==3.8.0

**Comment by netwang** [comment]
here is the requirements.txt. Could you help me to check which package is not compatible with eventlet? Thanks!

atomicwrites==1.4.0
attrs==21.4.0
bidict==0.22.0
click==8.1.3
colorama==0.4.5
cx-Oracle==8.3.0
dnspython==2.2.1
eventlet==0.33.1
Flask==2.1.2
Flask-Cors==3.0.10
Flask-SocketIO==5.2.0
greenlet==1.1.2
importlib-metadata==4.12.0
iniconfig==1.1.1
itsdangerous==2.1.2
Jinja2==3.1.2
ldap3==2.9.1
MarkupSafe==2.1.1
numpy==1.23.0
packaging==21.3
pandas==1.4.3
pip==22.0.4
pluggy==1.0.0
py==1.11.0
pyasn1==0.4.8
PyJWT==2.4.0
pyparsing==3.0.9
pytest==7.1.2
python-dateutil==2.8.2
python-engineio==4.3.2
python-socketio==5.6.0
pytz==2022.1
setuptools==58.1.0
six==1.16.0
tabulate==0.8.10
tomli==2.0.1
Werkzeug==2.1.2
zipp==3.8.0


Sincerely,
Net Wang (Mingwang Wang)001-416-391-3755 Ext. 388(Office)
001-416-786-0319 (Cell)
 

    On Thursday, June 30, 2022 at 10:31:30 a.m. EDT, Miguel Grinberg ***@***.***> wrote:  
 
 


@netwang You have an issue between eventlet and one or more packages that you are using. This package has nothing to do with this problem. You either need to ensure that all the packages that you use are compatible with eventlet, or else not use eventlet.

**Comment by miguelgrinberg** [comment]
@netwang I'm sorry, I can't go through every package and check, as it is too time consuming. If you are using any packages that are written in native (C/C++) code those are likely suspects to be incompatible with eventlet. If you really don't understand how eventlet works and why compatibility is an issue, then I recommend that you don't use it, and then everything should work just fine.

**Comment by netwang** [comment]
solved by using celery

celery = make_celery(app)

@celery.task(name="task.message")
def push_to_client(group_name, message_name, jsn):
    socketio.emit(message_name, jsn, to=group_name)

    # not work
    #socketio1 = SocketIO(message_queue='amqp://')
    #socketio1.emit(message_name, jsn, to=group_name)

    # not work
    #socketio.start_background_task(socketio.emit, message_name, jsn, to=group_name)

Thanks!

**Comment by netwang** [comment]
I successfully used Flask and Flask-Socketio with eventlet on Windows. I want to add async / await to access Oracle. As Miguel Grinberg said Flask-Socketio didn't support async / await. Need to use python-socketio which uses asyncio.

I successfully setup Flask with python-socketio in async_mode='threading'

sio = socketio.Server(async_mode='threading', logger=True, engineio_logger=True, cors_allowed_origins='*')

app.wsgi_app = socketio.WSGIApp(sio, app.wsgi_app, static_files=None, socketio_path='/QMOSDS/socket.io')

http://localhost:5000/QMOSDS/assets/images/QUAD-DS-logo-2.1.svg

http://localhost:5000/QMOSDS/socket.io/?EIO=4&transport=polling&t=OFMbSOj&sid=vY6aX2_07Gpk3-ZZAAAC http://localhost:5000/QMOSDS/api/Home/GetConfigurations (POST)

everything works well.

But I failed in async_mode='eventlet'

sio = socketio.Server(async_mode='eventlet', logger=True, engineio_logger=True, cors_allowed_origins='*')

socketio_app = socketio.WSGIApp(sio, app, static_files=None, socketio_path='/QMOSDS/socket.io')

eventlet.wsgi.server(eventlet.listen((HOST, PORT)), socketio_app)

405 Method not allowed because CORS allow methods: GET, HEAD, OPTIONS http://localhost:5000/QMOSDS/api/Home/GetConfigurations (POST)

If I changed to method "GET", then method is allowed but method not found

when call socketio.Server, how to set CORS allow methods? how to fix the method not found issue? Thanks!

**Comment by miguelgrinberg** [comment]
@netwang you are ignoring something very important. Flask doesn't support async/await. Eventlet does not support async/await. The threading mode in python-socketio does not support async/await. This will never work.

**Comment by netwang** [comment]
@miguelgrinberg Sorry, I explained my case wrongly. My code still in sync mode, not async / await.

I successfully used Flask and Flask-Socketio with eventlet on Windows. I am trying Flask and python-Socketio with eventlet on Windows in sync mode. I successfully setup Flask with python-socketio in **async_mode='threading'**

sio = socketio.Server(**async_mode='threading'**, logger=True, engineio_logger=True, **cors_allowed_origins='*'**)

app.wsgi_app = socketio.WSGIApp(sio, app.wsgi_app, static_files=None, socketio_path='/**QMOSDS**/socket.io')

http://localhost:5000/**QMOSDS**/assets/images/QUAD-DS-logo-2.1.svg

http://localhost:5000/**QMOSDS**/socket.io/?EIO=4&transport=polling&t=OFMbSOj&sid=vY6aX2_07Gpk3-ZZAAAC http://localhost:5000/**QMOSDS**/api/Home/GetConfigurations (POST)

everything works well.

But I failed in **async_mode='eventlet'**

sio = socketio.Server(**async_mode='eventlet'**, logger=True, engineio_logger=True, cors_allowed_origins='*')

socketio_app = socketio.WSGIApp(sio, app, static_files=None, socketio_path='/**QMOSDS**/socket.io')

eventlet.wsgi.server(**eventlet.listen((HOST, PORT)**), socketio_app)

405 Method not allowed because CORS allow methods: GET, HEAD, OPTIONS http://localhost:5000/QMOSDS/api/Home/GetConfigurations (POST)

If I changed to method "GET", then method is allowed but method not found

**how to add 'QMOSDS' subdirectory into eventlet.listen((HOST, PORT)) ??**

Thanks!

**Comment by miguelgrinberg** [comment]
@netwang The error is not in the Socket.IO endpoint, it is for an endpoint of your own Flask application, correct? So the way to address the error is to configure CORS for your Flask application. Have you done that? The Flask-CORS extension can be useful.
