### ISSUE TITLE
How many rooms can I realistically have?

### ISSUE THREAD

**Issue by astrike30** [miguelgrinberg/Flask-SocketIO#661]
I am trying to make a mobile (iOS) chat app and so the rooms feature really sounds like an easy way to do things as it mostly removes the need to handle client IDs etc. But I'm not sure if the feature is really designed for having a handful of rooms or if it would scale up to a huge amount. What would happen if I (for the sake of argument) had a million rooms going on at once? Would that be feasible and if so what kind of resources would it require?

If this is not possible is there a way to say store all of the clientIDs (and abstract them away to a database) within a specific chat room and only broadcast new messages to them?

Thank you for the help and keep up the great work :)

**Comment by astrike30** [comment]
So you're saying that I could realistically have 100,000 rooms at a time using a reasonable number of resources (i.e the equivalent of alternative options not using rooms)? Thanks for the quick reply btw.

**Comment by miguelgrinberg** [comment]
Speaking in specific numbers is hard, because there are many factors that affect resource consumption. What I'm saying is that rooms do not need significant resources.

Also important to note is that if your server process becomes too resource constrained, you can add a second process, and keep scaling horizontally as much as you need.
