### ISSUE TITLE
Suggested Flask-SocketIO.room_members(room) function

### ISSUE THREAD

**Issue by leematthewshome** [miguelgrinberg/Flask-SocketIO#706]
I am writing a solution where a bunch of IoT devices will connect to a Flask-SocketIO server. Each subscribed user will have their own room which those devices will connect to. When a user browser logs onto the server they should be presented with a list of their devices currently connected to their room. While it is possible to list the rooms a SID is a member of, it seems there is no way to fetch a list of SIDs in a room (apologies if I am missing something here).

A function to fetch the list of SIDS in a room would be useful. Then I could get the device/user name for each SID from my Dict object and return a list of connected devices to the user when they connect to the room. Again, apologies if I missed this in the docs, but I have looked through a few times and didnt see anything similar.

**Comment by miguelgrinberg** [comment]
I have intentionally decided to not support this, because it is difficult and inefficient to compile the list of clients that are in a room when you are using more than one server. In a multi-server set up, clients are going to be managed randomly by any of the servers, so each server only knows about a subset of the members in the room.

On the other side, your application can easily keep track of room memberships, either in a memory data structure, or in a database if you have one.

**Comment by leematthewshome** [comment]
Thanks Miguel. Makes sense.
