### ISSUE TITLE
Using "emit" inside HTTP Request handler with gevent

### ISSUE THREAD

**Issue by halilozercan** [miguelgrinberg/Flask-SocketIO#710]
I have a question about a use case like the following

```
@app.route('/ping')
def ping():
    socketio.emit('ping event', {'data': 42}, namespace='/chat')
```

This example is given in the comments of emit function. My question is while using gevent, ```socketio.emit``` seems like is executed and interpreter does not hang but actual emitting happens after request is handled and returned. However in my use case, it needs to send the message during the request. Is there a way to achieve this behavior, instant emit, or gevent loop cannot handle emit and HTTP request at the same time?

Thanks.

**Comment by hextrim** [comment]
try to catch it at GET

**Comment by halilozercan** [comment]
> try to catch it at GET

I'm not sure what do you mean by that

**Comment by hextrim** [comment]
Sorry I did not read that you want to emit at the same moment as HTTP
request hits the server... Normally you just emit after method GET is
caught... sounds like you require very sophistocated solution.

On 25 May 2018 00:11, "Halil Ozercan" <notifications@github.com> wrote:

try to catch it at GET

I'm not sure what do you mean by that

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/miguelgrinberg/Flask-SocketIO/issues/710#issuecomment-391893499>,
or mute the thread

**Comment by halilozercan** [comment]
I figured out the problem and it wasn't about emit being delayed. Do not ever use ```time.sleep``` inside gevent context. Always use ```gevent.sleep```

**Comment by miguelgrinberg** [comment]
@halilozercan you can use `socketio.sleep()`, which always maps to the correct sleep function that is compatible with the async framework that you are using.
