### ISSUE TITLE
How to close a room ? 

### ISSUE THREAD

**Issue by bruno-siqueira-simples** [miguelgrinberg/Flask-SocketIO#744]
Hey guys, I need to close a room and disconnect all users who are in it, how do I do this?

**Comment by miguelgrinberg** [comment]
The [close_room()](https://flask-socketio.readthedocs.io/en/latest/#flask_socketio.close_room) function will close a room and remove all users from it. It will not disconnect the users from their Socket.IO connections though. Is that sufficient?

**Comment by bruno-siqueira-simples** [comment]
Yeah, thank you!! Is it possible to disconnect all clients and then delete the room ?

**Comment by miguelgrinberg** [comment]
If your application knows which users are in the room, you can call `disconnect()` on each of them. There is no mass disconnection feature at this time.

**Comment by bruno-siqueira-simples** [comment]
Okay, thank you very much for the help!!

**Comment by miguelgrinberg** [comment]
The socket is connected until one of the parties disconnects. Leaving sockets open consumes file handles, not a good idea to leave them open if they are not needed because file handles are a limited resource. For example, if you have a file handle leak, eventually you'll reach a point where the process will not be able to open any new connections.

**Comment by bruno-siqueira-simples** [comment]
Okay, thank you !! Can you tell me what would be the maximum number of simultaneous sockets?

**Comment by miguelgrinberg** [comment]
There is no maximum, the max is dictated by available memory, limit of file handles in the OS, etc.
