### ISSUE TITLE
Execution on main route is blocked

### ISSUE THREAD

**Issue by tobHai** [miguelgrinberg/Flask-SocketIO#749]
I'm trying to use flask-socketio for sending stats from the Keras.fit method.
Unfortunately I do not fully understand how to use the background_task.
If I am starting the background_task in a certain route, the message gets emitted, but the 'main' code doesn't get executed? Shouldn't the execution happen concurrently?

```
@app.route('/train', methods=['POST'])
@cross_origin()
def train():
    send_progress('hi')
    count = 0
    while count < 100
        count = count + 1
        # this never gets printed
        print ( str(count) )

def send_progress(msg):
    global thread
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(target=background_thread(msg))
 

def background_thread(msg):
    count = 0
    while True:
        count = count +1
        socketio.sleep(5)
        socketio.emit('count', count)
 
```
Thanks!

**Comment by dlpersson** [comment]
I cant explain it very technically but I believe the issue is with how you call background_thread. Because you call it with (msg) on the end it makes the program execute it, which blocks further execution until it completes. Generally when calling another thread you are going to want to pass any needed arguments using the *args and **kwargs methodology
Explained here:
https://pythontips.com/2013/08/04/args-and-kwargs-in-python-explained/

If you take a look at the definition in the source files you can see that it is set up to accept a variable amount of arguments: def start_background_task(self, target, *args, **kwargs):

This works:
@socketio.on('connect', namespace='/test')
def test_connect():
    global thread
    msg="Hello"
    with thread_lock:
        if thread is None:
            thread = socketio.start_background_task(target=background_thread, msg=msg)
    emit('my_response', {'data': 'Connected', 'count': 0})

def background_thread(msg):
    """Example of how to send server generated events to clients."""
    count = 0
    while True:
        print(msg)
        socketio.sleep(10)
        count += 1
        socketio.emit('my_response',
                      {'data': 'Server generated event', 'count': count},
                      namespace='/test')
