### ISSUE TITLE
the app start run error

### ISSUE THREAD

**Issue by davidzhang9990** [miguelgrinberg/Flask-SocketIO#818]
async_mode = None
app = Flask(name)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app, async_mode=async_mode)
thread = None

@app.route('/')
def index():
emit('response', {'code': '200', 'msg': 'start to process...'})
return render_template('index.html')

if name == "main":
socketio.run(app, host='0.0.0.0', debug=True, port=5001)

Error info:
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
E:\Project\JDGoods\venv\lib\site-packages\flask_socketio_init_.py:496: Warning: Silently ignoring app.run() because the application is run from the flask command line executable. Consider putting app.run() behind an if name == "main" guard to silence this warning.
use_reloader=use_reloader, **kwargs)

Environment
Python version: 2.7
Flask version: 1.0.2
Werkzeug version:1.0
Flask-SocketIO version 3.0.2

**Comment by miguelgrinberg** [comment]
This is due to a bug in Flask 1.0 and up that hasn't been fixed yet. Either downgrade to Flask 0.12.2, or start the application via `socketio.run(app)`.

**Comment by ColdSauce** [comment]
@miguelgrinberg can this be documented somewhere in either the README or the official documentation? It's frustrating that one has to stumble upon a random Github Issue to find this out.

**Comment by miguelgrinberg** [comment]
This is a corner case, very few people run into this problem because using this library without eventlet or gevent installed is unusual. Note the big warning that appears on your example above, instructing you to install on of these for better performance. When you have eventlet or gevent installed the `app.run()` call is not used, so this problem does not occur. I now realize that I should have also mentioned this above, sorry for the omission.
