### ISSUE TITLE
uwsgi max-requests and reload-on-rss

### ISSUE THREAD

**Issue by chenyuan53618** [miguelgrinberg/Flask-SocketIO#870]
Hello there, 
below is my uwsgi recipe:
```
[uwsgi]
http = :5000
master = true
max-requests = 600
reload-on-rss = 800
mount = /api=./wsgi.py
callable = app

manage-script-name = true
gevent = 3000
http-websockets = true
http-timeout = 100
listen = 1024

stats = :5001
stats-http = true
memory-report = true
chmod-socket = 666
buffer-size = 65536
logto = /volume/log/uwsgi.log
```
and the problem is:
After max-requests(the number of requests that server already served) or rss memory reachs 800 MB, the server will be trying to reload. It's fine if there is no websocket connection. However, if there is a "long run" websocket connection, the whole instance may stuck for 60 seconds and yell "waiting for xxx requests". And "BOOOOOOOOOOOM" after that.

And my question is:
Do I have to have reload mechanism? If so, how should I configure uwsgi so that my web app won't stuck.

**Comment by miguelgrinberg** [comment]
As far as I know there is no mechanism by which uWSGI can indicate to a websocket task that it needs to exit gracefully. I think this `max-requests` option is not designed to work with long running requests, such as those used by websocket or long-polling, because uWSGI wants to wait up to 60 seconds before giving up and killing the worker.
