### ISSUE TITLE
Ensuring messages from external processes are sent

### ISSUE THREAD

**Issue by pilpelbarkan** [miguelgrinberg/Flask-SocketIO#874]
Hey,

I'm running a flask-socketio server on several pods with redis, and when emitting from an external process I wanted to know if there was any way of knowing if the event was sent to anyone.

I can see that any processes sending this event to their connected sockets log the event - is there any way for me to hook into that and run some code of my own? (such as checking if a message confirm event was received after a few seconds)

I've also considered using redis to track which sockets are connected but it would still leave me guessing whether the message was sent and received.

Are there any other alternatives to making sure a message from an external process was sent?

**Comment by miguelgrinberg** [comment]
Here is the response I gave you on Stack Overflow:

> There is currently no mechanism to do what you ask, unfortunately.
> 
> I think you basically have two approaches to go about this:
> 
> Always run your emits from the main server(s). If you need to emit from an auxiliary process, use an IPC mechanism to notify the server so that it can run the emit on its behalf. And now you can use callbacks.
> 
> Ignore the callbacks, and instead have the client acknowledge receipt of the event by emitting back to the server.
> 
> Adding callback support for auxiliary processes should not be terribly difficult, by the way. I never needed that functionality myself and you are the first to ask about it. Maybe I should look into that at some point.

Since I replied I came up with yet another option.

You can connect your external process to the server as a client, instead of using the "emit-only" option. If this process is a client, it can emit an event to the server, which in turn the server can relay to the external client. When the client replies to the server, the server can once again relay the response to the external process, which is not another client and has full send and receive capabilities. What do you think?
