### ISSUE TITLE
Dynamic data and possible lost emits treatment

### ISSUE THREAD

**Issue by valentin-ballester** [miguelgrinberg/Flask-SocketIO#957]
Lets suppose i emit to a client and when i emit that client is in a no-network zone or he is in an elevator so he doesn't receive the emit, how does a socket based app should treat that scenario? 

should i load dynamic data that could change with emits on every connect instead on HTML? i mean every connect event on the front end uses a socket event to get the latest data. so if a re connection event happens i get the newest data even if the client wasn't fully online when the emit happened. Thanks.

**Comment by miguelgrinberg** [comment]
If the client's connection drops then you will receive a disconnect event on the server, and then and then another connect event when it reconnects. The disconnect event can take a while to arrive, it's not immediate because the server cannot detect when a client enters a no-signal zone.

**Comment by valentin-ballester** [comment]
so is my solution factible ? because even if the disconnect event takes a while the user will not recieve emit of updates and when the reconection takes place it is better to load the newest data right ?

**Comment by miguelgrinberg** [comment]
There are a few ways to implement this. Basically what you need is a way to synchronize the client with the server. The easiest way is for the server to send everything again on the connection event. A more elaborate solution can be implemented if you can assign version numbers to updates. The client can indicate what was the last version number if knows about and then the server can send all the updates that happened since that version.

**Comment by valentin-ballester** [comment]
ok,  thank you very much for everything, tomorrow my first client start to use my app. its a very small hospital here in Argentina, thanks for all the help you gave me answering always and with your tutorials.
