### ISSUE TITLE
event handler emit timeout

### ISSUE THREAD

**Issue by whyengineer** [miguelgrinberg/Flask-SocketIO#972]
Hi, my application will handle a event about 1min, first of 30s, the emit can send, but emit can't send data to client. my client is socket-io.js. the server no any error.  client can't receive.

**Comment by miguelgrinberg** [comment]
I don't understand what the problem is. Do you have any logs with error messages, or an example application I can use to reproduce the problem?

**Comment by whyengineer** [comment]
for example:
@socketio.on("event")
define eventHandle:
         #this handle maybe need 1min. 
         while time<1min:
             emit("response",cnt)
             sockeio.sleep(0)
             cnt++

in first of 30s , the emit is ok. but the else emit doesn't working.

**Comment by miguelgrinberg** [comment]
Are you using a proxy server such as nginx? The timeout might be there, this package does not enforce timeouts for handlers.

**Comment by whyengineer** [comment]
no any proxy, localhost test. the trouble fixed when i change the pint_timeout.

**Comment by BillSchumacher** [comment]
The issue with this is Redis, they implemented a timeout on pubsub which defaults to the connection timeout.

I have a monkey patched version of  def _redis_listen_with_retries(self):, well actually a bit more since I needed Sentinel support with passwords. If you want me to package it into a PR I can, but I'm parsing the connection URL in a way that nobody else does so that I can get the sentinel password, Redis password and master name from the connection URL.
`
            except redis.exceptions.TimeoutError:
                logger.error('Cannot receive from redis... socket read timeout '
                             'retrying in {} secs'.format(retry_sleep))
                connect = True
                time.sleep(retry_sleep)
                retry_sleep *= 2
                if retry_sleep > 60:
                    retry_sleep = 60
`
